
<section id="activedirectory">
	<div class="page-header">
		<h1>
			Active directory <small>taken</small>
		</h1>
	</div>

	<div class="row">
		<div class="span12">

			<label class="checkbox"><input name="" type="checkbox"  value=""> Account maken
			</label>
			
			

			<label class="checkbox"><input name="" type="checkbox" data-toggle="collapse" data-target="#demo" value=""> Homedir maken
			</label>
			
			<div id="demo" class="collapse out">
			
			<form class="form-horizontal"
	action="<?php echo $this->SE_path . "/usertasks/posttasks" ?>"
	method="post" id="formAddUser">
	<fieldset>
		<legend>Homefolder</legend>

		<div class="control-group">
			<label class="control-label" for="server">Server</label>
			<div class="controls">
				<input id="server" name="server" class="input-xlarge" type="text"
					value="<?php echo $this->defaults->server; ?>">
					<p class="help-block "><i>server.domain.example</i></p>
			</div>
			
		</div>
		
		<div class="control-group">
			<label class="control-label" for="serverpath">Homefolder pad op server</label>
			<div class="controls">
			<div class="input-append">
				<input id="serverpath" name="serverpath" class="input-xlarge" type="text"
					value="<?php echo $this->defaults->serverpath; ?>"><span class="add-on">\<?php echo $this->person->getAccountUsername(); ?></span>
					<p class="help-block "><i>c:\pad\naar\homefolders</i></p>
					</div>
			</div>
		</div>

		<div class="control-group">
			<label class="control-label" for="scanpath">Scanpad op server</label>
			<div class="controls">
				<input id="scanpath" name="scanpath" class="input-xlarge" type="text"
					value="<?php echo $this->defaults->scanpath; ?>">
					<p class="help-block "><i>c:\pad\naar\scanshare</i></p>
			</div>
		</div>
		
				<div class="control-group">
			<label class="control-label" for="wwwpath">WWW pad op server</label>
			<div class="controls">
				<input id="wwwpath" name="wwwpath" class="input-xlarge" type="text"
					value="<?php echo $this->defaults->wwwpath; ?>">
					<p class="help-block "><i>c:\pad\naar\wwwshare</i></p>
			</div>
		</div>

	
	
	

		
	
	</fieldset>
		
</form>
			
			</div>
			
			<label class="checkbox"><input name="" type="checkbox" value=""> Homedir verplaatsen
			</label>

			<label class="checkbox"><input name="" type="checkbox" value=""> Upload & Download folders maken
			</label>

		</div>
	</div>
</section>

<section id="smartschool">
	<div class="page-header">
		<h1>
			Smartschool <small>taken</small>
		</h1>
	</div>

	<div class="row">
		<div class="span12">

			<label class="checkbox"><input name="" type="checkbox" value=""> Account maken
			</label>
			
		</div>
	</div>
</section>

<section id="googleapps">
	<div class="page-header">
		<h1>
			Google <small>taken</small>
		</h1>
	</div>

	<div class="row">
		<div class="span12">

			<label class="checkbox"><input name="" type="checkbox" value=""> Account maken
			</label>
			
		</div>
	</div>
</section>
