<?php 
use solideagle\utilities\SuperEntities;

?>

<script>
	$(function(){

		var selectedArr = new Array();

                $(".selectUser:checked").each( 
                    function(k,v) { 
                        selectedArr.push($(v).attr("value"));
                    } 
                );

		if(selectedArr.length > 0)
		{
			$('#myModal').modal('show');
                        
                        $("#deleteadsure").hide();
                        $("#deletesssure").hide();
                        $("#deletegappsure").hide();
                        $("#radioAdEnableAccounts").hide();
                        $("#radioAdDisableAccounts").hide();

                        $("#blnDeleteAd").click(function(){
                                $("#deleteadsure").toggle();
                                $("#blnDeleteAdSure").removeAttr("checked");
                        });
                        $("#blnAdMultipleEnableDisable").click(function(){
                                $("#radioAdEnableAccounts").toggle();
                                $("#radioAdDisableAccounts").toggle();
                                $("#optionAdMultipleEnable").removeAttr("checked");
                                $("#optionAdMultipleDisable").removeAttr("checked");
                        });
                        $("#blnDeleteSs").click(function(){
                                $("#deletesssure").toggle();
                                $("#blnDeleteSsSure").removeAttr("checked");
                        });
                        $("#blnDeleteGapp").click(function(){
                                $("#deletegappsure").toggle();
                                $("#blnDeleteGappSure").removeAttr("checked");
                        });
		}else{
			alert("Geen gebruikers geselecteerd");

		}

					
		$("#formTasks").ajaxForm({
			data:  {"users":selectedArr},
			success: function(responseText, statusText, xhr, $form) { 

				if(responseText.length > 0)
				{
					alert(responseText);
				}else{
					$('#myModal').modal('hide');
					updateTree();
				}
				
	    } });

		
	});

</script>

<form
	class="form-horizontal"
	action="<?php echo $this->SE_path . "/usertasks/posttasks" ?>"
	method="post"
	id="formTasks">

	<div
		class="hide SEsupermodal"
		id="myModal">
		<div>
			<div class="modal-header">
				<a
					class="close"
					data-dismiss="modal">×</a>
				<h3 id="modaltitle">Taken uitvoeren</h3>
			</div>
			<div class="modal-body">


				<section id="activedirectory">
					<div class="page-header">
						<h1>
							Active directory <small>taken</small>
						</h1>
					</div>

					<div class="row">
						<div class="span12">
                                                            
                                                            <label class="checkbox">
                                                                    <input
                                                                            name="createAdAccount"
                                                                            type="checkbox"
                                                                            value="true">
                                                                    Account maken
                                                            </label>
                                                            <label class="checkbox">
                                                                Account verwijderen
                                                                <input name="deleteAdAccount" id="blnDeleteAd" type="checkbox" value="false">
                                                            </label>
                                                            <div class="control-group error" id="deleteadsure">
                                                                <label class="checkbox error" id="lbldeleteadsure">
                                                                        Ja, ik ben zeker
                                                                        <input id="blndeleteadsure" name="deleteAdAccountSure" type="checkbox" value="false">
                                                                </label>  
                                                            </div>

                                                            <label class="checkbox">
                                                                    Account deactiveren
                                                                    <input name="blnAdDisable" id="blnAdDisable" type="checkbox" >
                                                            </label>
                                                            <label class="checkbox">
                                                                    Account activeren
                                                                    <input name="blnAdEnable" id="blnAdEnable" type="checkbox" >
                                                            </label>

                                                        <label class="checkbox">
                                                                <input
                                                                        name="createAdHomedir"
                                                                        type="checkbox"
                                                                        data-toggle="collapse"
                                                                        data-target="#adHomeDirParams"
                                                                        value="true">
                                                                Homedir maken
                                                        </label>

							<div
								id="adHomeDirParams"
								class="collapse out">
								<fieldset>
									<legend>Homefolder</legend>

									<div class="control-group">
										<label
											class="control-label"
											for="server">Server</label>
										<div class="controls">
											<input
												id="server"
												name="HomefolderServer"
												class="input-xlarge"
												type="text"
												value="<?php echo SuperEntities::encode($this->defaults->server); ?>">
											<p class="help-block ">
												<i>server.domain.example</i>
											</p>
										</div>

									</div>

									<div class="control-group">
										<label
											class="control-label"
											for="serverpath">Homefolder pad op server</label>
										<div class="controls">
											<div class="input-append">
												<input
													id="serverpath"
													name="HomefolderPath"
													class="input-xlarge"
													type="text"
													value="<?php echo SuperEntities::encode($this->defaults->serverpath); ?>"
													><span class="add-on">\janssensj</span>
												<p class="help-block ">
													<i>c:\pad\naar\homefolders</i>
												</p>
											</div>
										</div>
									</div>

									<div class="control-group">
										<label
											class="control-label"
											for="scanpath">Scanpad op server</label>
										<div class="controls">
											<input
												id="scanpath"
												name="ScanSharePath"
												class="input-xlarge"
												type="text"
												value="<?php echo SuperEntities::encode($this->defaults->scanpath); ?>">
											<p class="help-block ">
												<i>c:\pad\naar\scanshare</i>
											</p>
										</div>
									</div>

									<div class="control-group">
										<label
											class="control-label"
											for="wwwpath">WWW pad op server</label>
										<div class="controls">
											<input
												id="wwwpath"
												name="WWWSharePath"
												class="input-xlarge"
												type="text"
												value="<?php echo SuperEntities::encode($this->defaults->wwwpath); ?>">
											<p class="help-block ">
												<i>c:\pad\naar\wwwshare</i>
											</p>
										</div>
									</div>

								</fieldset>

							</div>
							
							<label class="checkbox">
								<input
									name="createUpDownFolders"
									type="checkbox"
									data-toggle="collapse"
									data-target="#adUpDownParams"
									value="true">
								Upload &amp; Downloadfolders maken
							</label>

							<div
								id="adUpDownParams"
								class="collapse out">
								<fieldset>
									<legend>Upload & Downloadfolders</legend>

									<div class="control-group">
										<label
											class="control-label"
											for="server">Uploadpad</label>
										<div class="controls">
											<input
												id="server"
												name="UploadSharePath"
												class="input-xlarge"
												type="text"
												value="<?php echo SuperEntities::encode($this->defaults->uploadpath); ?>">
											<p class="help-block ">
												<i>c:\pad\naar\upload</i>
											</p>
										</div>
										
											<label
											class="control-label"
											for="server">Downloadpad</label>
										<div class="controls">
											<input
												id="server"
												name="DownloadSharePath"
												class="input-xlarge"
												type="text"
												value="<?php echo SuperEntities::encode($this->defaults->downloadpath); ?>">
											<p class="help-block ">
												<i>c:\pad\naar\download</i>
											</p>
										</div>

									</div>

								</fieldset>

							</div>

							<label class="checkbox">
								<input
									name=""
									type="checkbox"
									value="">
								Homedir verplaatsen
							</label>

						</div>
					</div>
				</section>

				<section id="smartschool">
					<div class="page-header">
						<h1>
							Smartschool <small>taken</small>
						</h1>
					</div>

					<div class="row">
						<div class="span12">
                                                    
                                                    <?php if($this->hasSsAccount)
                                                    {?>
                                                        <label class="checkbox">
                                                            Account verwijderen
                                                            <input name="deleteSSAccount" id="blnDeleteSs" type="checkbox" value="false">
                                                        </label>
                                                        <div class="control-group error" id="deletesssure">
                                                            <label class="checkbox error" id="lbldeletesssure">
                                                                    Ja, ik ben zeker
                                                                    <input id="blndeletesssure" name="deleteSSAccountSure" type="checkbox" value="false">
                                                            </label>  
                                                        </div>
                                                        <label class="checkbox">
                                                            <?php if($this->hasSsAccountEnabled)
                                                            {?>
                                                                Account deactiveren
                                                                <input name="blnSsDisable" id="blnSsDisable" type="checkbox" >
                                                            <?php
                                                            }
                                                            else
                                                            {?>
                                                                Account activeren
                                                                <input name="blnSsEnable" id="blnSsEnable" type="checkbox" >
                                                            <?php
                                                            }?>
                                                        </label>
                                                    <?php
                                                    }
                                                    else
                                                    {?>
                                                        <label class="checkbox">
                                                            <input
                                                                name="createSSAccount"
                                                                type="checkbox"
                                                                value="true">
                                                            Account maken
                                                        </label>
                                                    <?php
                                                    }
                                                    ?>

						</div>
					</div>
				</section>

				<section id="googleapps">
					<div class="page-header">
						<h1>
							Google <small>taken</small>
						</h1>
					</div>

					<div class="row">
                                            <div class="span12">
                                                
                                                <?php if($this->hasSsAccount)
                                                {?>
                                                    <label class="checkbox">
                                                        Account verwijderen
                                                        <input name="deleteGappAccount" id="blnDeleteGapp" type="checkbox" value="false">
                                                    </label>
                                                    <div class="control-group error" id="deletegappsure">
                                                        <label class="checkbox error" id="lbldeletegappsure">
                                                                Ja, ik ben zeker
                                                                <input id="blndeletegappsure" name="deleteGappAccountSure" type="checkbox" value="false">
                                                        </label>  
                                                    </div>
                                                    <label class="checkbox">
                                                        <?php if($this->hasGappAccountEnabled)
                                                        {?>
                                                            Account deactiveren
                                                            <input name="blnGappDisable" id="blnGappDisable" type="checkbox" >
                                                        <?php
                                                        }
                                                        else
                                                        {?>
                                                            Account activeren
                                                            <input name="blnGappEnable" id="blnGappEnable" type="checkbox" >
                                                        <?php
                                                        }?>
                                                    </label>
                                                <?php
                                                }
                                                else
                                                {?>
                                                    <label class="checkbox">
                                                        <input
                                                            name="createGappAccount"
                                                            type="checkbox"
                                                            value="true">
                                                        Account maken
                                                    </label>
                                                <?php
                                                }
                                                ?>

						</div>
					</div>
				</section>

			</div>
			<div class="modal-footer">
				<a
					href="#"
					class="btn"
					data-dismiss="modal">Annuleren</a>
				<button
					class="btn btn-primary"
					type="submit">Uitvoeren</button>
			</div>
		</div>
	</div>


</form>
