<?php 
use solideagle\utilities\SuperEntities;

?>

<script>
	$(function(){


		/*var total = "";
		$("input").each(function(k,v){

			total += $(this).attr("name") + "\n";
		});

		alert(total);*/
            
   		var selectedArr = new Array();

   		var manageTemplate = <?php echo $this->manageTemplate ?>;
              
		if(!manageTemplate)
		{
			$(".selectUser:checked").each( 
				function(k,v) { 
					selectedArr.push($(v).attr("value"));
				} 
			);
		}

		if(selectedArr.length > 0)
		{
                        $('#myModal').modal('show');

                        $("#deleteadsure").hide();
                        $("#deletesssure").hide();
                        $("#deletegappsure").hide();

                        $("#blnDeleteAd").click(function(){
                                $("#deleteadsure").toggle();
                                $("#blnDeleteAdSure").removeAttr("checked");
                        });
                        $("#blnAdMultipleEnableDisable").click(function(){
                                $("#radioAdEnableAccounts").toggle();
                                $("#radioAdDisableAccounts").toggle();
                                $("#optionAdMultipleEnable").removeAttr("checked");
                                $("#optionAdMultipleDisable").removeAttr("checked");
                        });
                        $("#blnDeleteSs").click(function(){
                                $("#deletesssure").toggle();
                                $("#blnDeleteSsSure").removeAttr("checked");
                        });
                        $("#blnDeleteGapp").click(function(){
                                $("#deletegappsure").toggle();
                                $("#blnDeleteGappSure").removeAttr("checked");
                        });
		}
		else if(manageTemplate)
		{
            // manage templates
                       
                                $('#myModal').modal('show');
                             
                                $("#deleteadsure").hide();
                                $("#deletesssure").hide();
                                $("#deletegappsure").hide();
                       
		}else{      
			alert("Geen gebruikers geselecteerd");
		}
	
		$("#formTasks").ajaxForm({
			data:  {"users":selectedArr},
			success: function(responseText, statusText, xhr, $form) { 

				if(responseText.length > 0)
				{
					alert(responseText);
				}else{
					$('#myModal').modal('hide');
					updateTree();
				}
				
	    } });

		
	});

	<?php /*function loadTemplate(templatename)
	{
		$.getJSON("<?php echo $this->SE_path . '/tasktemplate/gettemplate' ?>",{'templatename':templatename} ,

                function(data)  {
                	 $.each(data, function(key, val) {
                		 if(key=="templateConfig")
                		 {
                			 $.each(val, function(param, value) {

                    			var elem = $("#"+ param);
                    			
                    			if(elem.attr("type") == "text")
                    			{
                        			alert("TEXT: " + elem + " " + value)
                    				elem.attr("value",value);
                    			}else if(elem.attr("type") == "checkbox")
                    			{                			
                        			if(value)
                        			{
                        				elem.attr("checked","checked");
                        			}
                    				
                    			}else{
                    				alert("UNK: " + elem.attr("type")  + " " + value)
                    			}
                				
                 				
                			 });
                		 }
                    });
                }
        );
	}*/ ?>
</script>

<form
	class="form-horizontal"
	action="<?php echo $this->SE_path . "/usertasks/posttask" ?>"
	method="post"
	id="formTasks">

	<div
		class="hide SEsupermodal"
		id="myModal">
		<div>
			<div class="modal-header">
				<a
					class="close"
					data-dismiss="modal">×</a>
				<?php if($this->manageTemplate)
                {?>
				<h3 id="modaltitle">Beheer taak templates</h3>
				<?php
                }else{?>
				<h3 id="modaltitle">Taken uitvoeren</h3>
				<?php }?>
			</div>

			<div class="modal-body">

				<?php if($this->templatename != NULL || $this->manageTemplate)
                {?>
				<section id="tasktemplate">
					<div class="page-header">
						<h1>Taken templates</h1>
					</div>

					<div class="control-group">
						<label
							class="control-label"
							for="txtName">Naam template</label>
						<div class="controls">

							<input
								id="txtName"
								name="txtName"
								class="input-xlarge"
								type="text"
								<?php echo $this->manageTemplate ? "" : "readonly = 'readonly'" ?>"
								value="<?php  echo $this->templatename  ?>">
						</div>
					</div>
				</section>
				<?php }?>

				<section id="activedirectory">
					<div class="page-header">
						<h1>
							Active directory <small>taken</small>
						</h1>
					</div>

					<div class="row">
						<div class="span12">

						
				
						
							<?php if ($this->multipleAccountsSelected || !$this->hasAdAccount || $this->manageTemplate)
                            {?>
							<label class="checkbox">
								<input
									name="createAdAccount"
									id="createAdAccount"
									type="checkbox"
									<?php echo $this->defaults->createAdAccount ? "checked='checked'" : "" ?>>
								Account maken
							</label>

							<?php 
                            }

                            if ($this->multipleAccountsSelected || $this->hasAdAccount || $this->manageTemplate)
                            {?>
							<label class="checkbox">
								Account verwijderen
								<input
									name="deleteAdAccount"
									id="blnDeleteAd"
									type="checkbox"
									value="false"
									<?php echo $this->defaults->deleteAdAccount ? "checked='checked'" : "" ?>>
							</label>
							<div
								class="control-group error"
								id="deleteadsure">
								<label
									class="checkbox error"
									id="lbldeleteadsure">
									Ja, ik ben zeker
									<input
										id="blndeleteadsure"
										name="deleteAdAccountSure"
										type="checkbox"
										value="false">
								</label>
							</div>
							<?php
                            }
                            if ($this->multipleAccountsSelected || $this->hasAdAccountEnabled || $this->manageTemplate)
                           	{?>
							<label class="checkbox">
								Account deactiveren
								<input
									name="disableAdAccount"
									id="blnAdDisable"
									type="checkbox"
									<?php echo $this->defaults->disableAdAccount ? "checked='checked'" : "" ?>>
							</label>
							<?php
                           	}
                           	if($this->multipleAccountsSelected || !$this->hasAdAccountEnabled || $this->manageTemplate)
                            {?>
							<label class="checkbox">
								Account activeren
								<input
									name="enableAdAccount"
									id="blnAdEnable"
									type="checkbox"
									<?php echo $this->defaults->enableAdAccount ? "checked='checked'" : "" ?>>
							</label>
							<?php
                            }?>

							<label class="checkbox">
								<input
									name="createAdHomedir"
									type="checkbox"
									data-toggle="collapse"
									data-target="#adHomeDirParams"
									value="true"
									<?php echo $this->defaults->createAdHomedir ? "checked='checked'" : "" ?>>
								Homedir maken
							</label>

							<div
								id="adHomeDirParams"
								class="collapse out">
								<fieldset>
									<legend>Homefolder</legend>

									<div class="control-group">
										<label
											class="control-label"
											for="server">Server</label>
										<div class="controls">
											<input
												id="server"
												name="homefolderServer"
												class="input-xlarge"
												type="text"
												value="<?php echo SuperEntities::encode($this->defaults->homefolderServer); ?>">
											<p class="help-block ">
												<i>server.domain.example</i>
											</p>
										</div>
									</div>

									<div class="control-group">
										<label
											class="control-label"
											for="serverpath">Homefolder pad op server</label>
										<div class="controls">
											<div class="input-append">
												<input
													id="serverpath"
													name="homefolderPath"
													class="input-xlarge"
													type="text"
													value="<?php SuperEntities::encode($this->defaults->homefolderPath); ?>">
												<span class="add-on">\janssensj</span>
												<p class="help-block ">
													<i>c:\pad\naar\homefolders</i>
												</p>
											</div>
										</div>
									</div>

									<div class="control-group">
										<label
											class="control-label"
											for="scanpath">Scanpad op server</label>
										<div class="controls">
											<input
												id="scanpath"
												name="scanSharePath"
												class="input-xlarge"
												type="text"
												value="<?php SuperEntities::encode($this->defaults->scanSharePath); ?>">
											<p class="help-block ">
												<i>c:\pad\naar\scanshare</i>
											</p>
										</div>
									</div>

									<div class="control-group">
										<label
											class="control-label"
											for="wwwpath">WWW pad op server</label>
										<div class="controls">
											<input
												id="wwwpath"
												name="wwwSharePath"
												class="input-xlarge"
												type="text"
												value="<?php SuperEntities::encode($this->defaults->wwwSharePath); ?>">
											<p class="help-block ">
												<i>c:\pad\naar\wwwshare</i>
											</p>
										</div>
									</div>

								</fieldset>

							</div>

							<label class="checkbox">
								<input
									name="createUpDownFolders"
									type="checkbox"
									data-toggle="collapse"
									data-target="#adUpDownParams"
									value="true"
									<?php echo $this->defaults->createUpDownFolders ? "checked='checked'" : "" ?>>
								Upload &amp; Downloadfolders maken
							</label>

							<div
								id="adUpDownParams"
								class="collapse out">
								<fieldset>
									<legend>Upload & Downloadfolders</legend>

									<div class="control-group">
										<label
											class="control-label"
											for="server">Uploadpad</label>
										<div class="controls">
											<input
												id="server"
												name="uploadSharePath"
												class="input-xlarge"
												type="text"
												value="<?php echo SuperEntities::encode($this->defaults->uploadSharePath); ?>">
											<p class="help-block ">
												<i>c:\pad\naar\upload</i>
											</p>
										</div>

										<label
											class="control-label"
											for="server">Downloadpad</label>
										<div class="controls">
											<input
												id="server"
												name="downloadSharePath"
												class="input-xlarge"
												type="text"
												value="<?php echo SuperEntities::encode($this->defaults->downloadSharePath); ?>">
											<p class="help-block ">
												<i>c:\pad\naar\download</i>
											</p>
										</div>

									</div>

								</fieldset>

							</div>

							<label class="checkbox">
								<input
									name="moveAdHomedir"
									type="checkbox"
									value="true"
									<?php echo $this->defaults->moveAdHomedir ? "checked='checked'" : "" ?>>
								Homedir verplaatsen
							</label>

						</div>
					</div>
				</section>

				<section id="smartschool">
					<div class="page-header">
						<h1>
							Smartschool <small>taken</small>
						</h1>
					</div>

					<div class="row">
						<div class="span12">

							<?php if ($this->multipleAccountsSelected || !$this->hasSsAccount || $this->manageTemplate)
                            {?>
							<label class="checkbox">
								<input
									name="createSsAccount"
									type="checkbox"
									value="true"
									<?php echo $this->defaults->createSsAccount ? "checked='checked'" : "" ?>>
								Account maken
							</label>
							<?php 
                            }
                            if ($this->multipleAccountsSelected || $this->hasSsAccount || $this->manageTemplate)
                            {?>
							<label class="checkbox">
								Account verwijderen
								<input
									name="deleteSsAccount"
									id="blnDeleteSs"
									type="checkbox"
									value="false"
									<?php echo $this->defaults->deleteSsAccount ? "checked='checked'" : "" ?>>
							</label>
							<div
								class="control-group error"
								id="deletesssure">
								<label
									class="checkbox error"
									id="lbldeletesssure">
									Ja, ik ben zeker
									<input
										id="blndeletesssure"
										name="deleteSsAccountSure"
										type="checkbox"
										value="false">
								</label>
							</div>
							<?php
                                                    }if ($this->multipleAccountsSelected || $this->hasSsAccountEnabled || $this->manageTemplate)
                                                    {?>
							<label class="checkbox">
								Account deactiveren
								<input
									name="disableSsAccount"
									id="blnSsDisable"
									type="checkbox"
									<?php echo $this->defaults->disableSsAccount ? "checked='checked'" : "" ?>>
							</label>
							<?php
                            }
                            if($this->multipleAccountsSelected || !$this->hasSsAccountEnabled || $this->manageTemplate)
                            {?>
							<label class="checkbox">
								Account activeren
								<input
									name="enableSsAccount"
									id="blnSsEnable"
									type="checkbox"
									<?php echo $this->defaults->enableSsAccount ? "checked='checked'" : "" ?>>
							</label>
							<?php
                            }?>

						</div>
					</div>
				</section>

				<section id="googleapps">
					<div class="page-header">
						<h1>
							Google <small>taken</small>
						</h1>
					</div>

					<div class="row">
						<div class="span12">
							<?php if ($this->multipleAccountsSelected || !$this->hasGappAccount || $this->manageTemplate)
                                                {?>
							<label class="checkbox">
								<input
									name="createGappAccount"
									type="checkbox"
									value="true"
									<?php echo $this->defaults->createGappAccount ? "checked='checked'" : "" ?>>
								Account maken
							</label>
							<?php 
                            }
                            if ($this->multipleAccountsSelected || $this->hasGappAccount || $this->manageTemplate)
                            {?>
							<label class="checkbox">
								Account verwijderen
								<input
									name="deleteGappAccount"
									id="blnDeleteGapp"
									type="checkbox"
									value="false"
									<?php echo $this->defaults->deleteGappAccount ? "checked='checked'" : "" ?>>
							</label>
							<div
								class="control-group error"
								id="deletegappsure">
								<label
									class="checkbox error"
									id="lbldeletegappsure">
									Ja, ik ben zeker
									<input
										id="blndeletegappsure"
										name="deleteGappAccountSure"
										type="checkbox"
										value="false">
								</label>
							</div>
							<?php
                            }
                            if ($this->multipleAccountsSelected || $this->hasGappAccountEnabled || $this->manageTemplate)
                           {?>
							<label class="checkbox">
								Account deactiveren
								<input
									name="disableGappAccount"
									id="blnGappDisable"
									type="checkbox"
									<?php echo $this->defaults->disableGappAccount ? "checked='checked'" : "" ?>>
							</label>
							<?php
                            }
                            if($this->multipleAccountsSelected || !$this->hasGappAccountEnabled || $this->manageTemplate)
                           {?>
							<label class="checkbox">
								Account activeren
								<input
									name="enableGappAccount"
									id="blnGappEnable"
									type="checkbox"
									<?php echo $this->defaults->enableGappAccount ? "checked='checked'" : "" ?>>
							</label>
							<?php }?>
						</div>
					</div>
				</section>
			</div>
			<div class="modal-footer">
				<a
					href="#"
					class="btn"
					data-dismiss="modal">Annuleren</a>
				<button
					class="btn btn-primary"
					id="submitBtn"
					name="submitBtn"
					type="submit"
					value="<?php 
                                            if($this->manageTemplate)
                                                echo ($this->addtemplate) ? "addTemplate" : "editTemplate";
                                            else
                                                echo "addTasks"
                                        ?>">Uitvoeren</button>
			</div>
		</div>
	</div>

</form>
