<?php
$this->headScript()->appendFile($this->SE_path . "/js/groupsandusers.js");
?>

<script>
$(function() {

	//tell JS the path to our application
	//only use when zend/public is not the root folder on the http server
	//SEpath = "<?php echo $this->SE_path; ?>";
	
	showUsers();
	updateTree();
	makeLinks();

	
});
</script>

<div class="alert">
	<a
		class="close"
		data-dismiss="alert">×</a> <strong>Warning!</strong> <span id="bofhexcuse"></span>
</div>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span3">
			<h1>Groepen</h1>

			<div id="grouptree">
				<!-- tree will be rendered here -->
			</div>
		</div>
		<div class="span9">

			<ul class="nav nav-pills ">
				<li><h2 style="line-height: 30px">
						Groep <span id="groupname"></span>
					</h2></li>


				<li
					class="dropdown"
					id="menu1"><a
					class="dropdown-toggle"
					data-toggle="dropdown"
					href="#menu1">Groep<b class="caret"></b>
				</a>
					<ul class="dropdown-menu">
						<li><a
							id="CreateUserLink"
							href="#"><i class="icon-user"></i> Gebruiker maken</a></li>
						<li class="divider"></li>
						<li><a
							href="#"
							id="mailGroup"> <i class="icon-envelope"></i> Groep mailen
						</a>
						</li>
						<li class="divider"></li>
						<li><a
							id="CreateSubGroupLink"
							href="#"><i class="icon-plus"></i> Subgroep maken</a></li>
						<li><a
							id="EditGroupLink"
							href="#"><i class="icon-pencil"></i> Groep bewerken</a></li>
						<li><a
							id="RemoveGroupLink"
							href="#"> <i class="icon-remove"></i> Groep verwijderen
						</a></li>

					</ul>
				</li>



				<li
					class="dropdown"
					id="menu2"><a
					class="dropdown-toggle"
					data-toggle="dropdown"
					href="#menu2">Taken uitvoeren<b class="caret"></b>
				</a>
					<ul class="dropdown-menu">

						<li class="nav-header"><span style="white-space: nowrap">Geselecteerde gebruikers</span></li>
						<li><a
							href="javascript:void(0)"
							id="RemoveUserLink"> <i class="icon-remove"></i> Verwijderen
						</a></li>
						<li><a
							id="MoveUserLink"
							href="#"><i class="icon-move"></i> Verplaatsen</a></li>
						<li><a
							id="ResetPwSelectedLink"
							href="#"><i class="icon-share-alt"></i> Wachtwoord reset</a></li>
						<li><a
							id="TaskForUser"
							href="#"><i class="icon-list-alt"></i> Custom taak</a></li>
						<li><a
							id="TemplateTaskForUser"
							href="#"><i class="icon-list-alt"></i> Template taak</a></li>

						<li class="nav-header"><span style="white-space: nowrap">Deze groep en subgroepen</span></li>

						<li><a
							href="javascript:void(0)"
							id="RemoveUsersInGroupLink"> <i class="icon-remove"></i>Verwijderen
						</a></li>
						<li><a
							id="MoveUsersInGroupLink"
							href="#"><i class="icon-move"></i>Verplaatsen</a></li>

						<li><a
							id="ResetPwGroupLink"
							href="#"><i class="icon-share-alt"></i> Wachtwoord reset</a>
						</li>
						<li><a
							id="TaskForGroup"
							href="#"><i class="icon-list-alt"></i> Custom taak</a>
						</li>
						<li><a
							id="TemplateTaskForGroup"
							href="#"><i class="icon-list-alt"></i> Template taak</a></li>
					</ul>
				</li>

			</ul>
			<div id="groepcontent">
				<table
					id='userstable'
					class='table'>
					<thead>
						<tr>
							<td><input
									type="checkbox"
									id="selectAllCheckbox" /></td>
							<td>ID <i class='icon-chevron-down'></i><i class='icon-chevron-up'></i>
							</td>
							<td>Voornaam <i class='icon-chevron-down'></i><i class='icon-chevron-up'></i>
							</td>
							<td>Achternaam <i class='icon-chevron-down'></i><i class='icon-chevron-up'></i>
							</td>
							<td>Gebruikersnaam <i class='icon-chevron-down'></i><i class='icon-chevron-up'></i>
							</td>
							<td>Platformstatus <i class='icon-chevron-down'></i><i class='icon-chevron-up'></i>
							</td>
							<td>Gemaakt op <i class='icon-chevron-down'></i><i class='icon-chevron-up'></i>
							</td>
						</tr>
					</thead>
				</table>
			</div>
		</div>
	</div>
</div>

<div id="modalholder"></div>

<div id="useractions">
	<ul class="nav nav-pills">
		<li class="dropdown">
			<ul class="dropdown-menu">
				<li><a
					href="javascript:void(0)"
					id="ViewUserLink"><i class="icon-user"></i> Bekijken</a></li>
				<li><a
					href="javascript:void(0)"
					id="EditUserLink"><i class="icon-pencil"></i> Bewerken</a></li>
				<li><a
					href="javascript:void(0)"
					id="ResetPwUserLink"><i class="icon-share-alt"></i> Wachtwoord reset</a></li>
			</ul>
		</li>
	</ul>
</div>

<div
	id="loadingHolder"
	style="display: none">
	<div class="SEsupermodal ">
		<div style="min-width: 500px;">
			<h2 style="padding: 20px">
				<img
					style="height: 25px;"
					src="<?php echo $this->SE_path; ?>/images/loading.gif"
					height="25px" />Loading...
			</h2>
		</div>
	</div>
	<div class="modal-backdrop in"></div>
</div>
