<?php use DataAccess\TaskQueue; ?>



<div class="page-header">
<h1>Dashboard</h1>
</div>


<div class="row-fluid">
	<div class="span12">
		<h2>Task queue</h2>


		<table class="table">
			<thead>
				<tr>
					<td>Task</td>
					<td>Configuratie</td>
					<td>Group id</td>
					<td>Person id</td>
					<td>Error count</td>
					<td>Error messages</td>
				</tr>
			</thead>
			<tbody>

			
				<?php 
				foreach ($this->taskQueue as $tq)
				{?>

				<tr <?php if($tq->getErrorCount()>0){echo 'class="alert alert-error"';} ?>>
					<td><?php echo $tq->getTask()->getPathScript() . $tq->getTask()->getName() ?>
					</td>
					<td><pre><?php var_dump( $tq->getConfiguration()) ?></pre>
					</td>
					<td><?php echo $tq->getGroupid() ?>
					</td>
					<td><?php echo $tq->getPersonid() ?>
					</td>
					<td><?php echo $tq->getErrorCount() ?>
					</td>
					<td><pre><?php echo $tq->getErrorMessages() ?></pre>
					</td>
				</tr>

				<?php } ?>
			</tbody>
		</table>
	</div>

	
</div>

