<?php $this->headTitle('Import staff'); ?>

<div>

	<div class="page-header">
		<h1>Staff importeren</h1>
	</div>
	
	<form
		class="form-horizontal"
		enctype="multipart/form-data"
		method="post">
		<fieldset>
			<legend>Stap 1: Upload CSV-bestand</legend>
			<div class="alert alert-error">

				<strong>Opgelet!</strong> Dit bestand moet opgeslaan zijn als UTF-8!
			</div>
			<div class="control-group">
				<label
					class="control-label"
					for="fileInput">CSV-bestand: </label>
				<div class="controls">
					<input
						id="fileInput"
						class="input-file"
						name="csvfile"
						type="file">
				</div>
			</div>

			<div class="form-actions">
				<button
					class="btn btn-primary"
					type="submit"
					name="submit"
					value="true">Bestand laden</button>
			</div>
		</fieldset>
	</form>


</div>

