<?php use solideagle\utilities\SuperEntities;
?>


<div>

	<div class="page-header">
		<h1>Klassen aanmaken</h1>
	</div>

	<form
		class="form-horizontal"
		enctype="multipart/form-data"
		method="post">
		<fieldset>
			<legend>Volgende klassen bestaan niet en zullen aangemaakt worden</legend>

			<div class="clearfix">
				<?php

				foreach($this->klassen as $klas)
				{
					?>

				<label
					class="control-label"
					for="checkbox">
					<?php echo $klas; ?>

					
				</label>
				<?php
				}

				?>

			</div>
			<div class="form-actions ">
				<button
					class="btn btn-primary"
					type="submit"
					name="submit"
					value="true">Klassen maken</button>
			</div>
		</fieldset>
	</form>

</div>



