<title>Solid Eagle</title>

<link rel="stylesheet" type="text/css" media="screen" href="../css/reset.css" />
<link rel="stylesheet" type="text/css" media="screen" href="../css/screen.css" />
<div id="wrapper">

    <div id="header">

        <h1>Centraal gebruikersbeheer DBZ</h1>
        
        <div id="loggedInAs">
            <p>Welkom, voornaam.naam <a href="#">logout</a></p>
        </div>
        
        <div id="menu">
            <ul>
                <li><a href="#">home</a></li>
                <li><a href="#">beheer accounts</a></li>
                <li><a href="#">configuratie</a></li>
            </ul>
            <div id="search">
                <form action="#" method="post" id="searchAccounts">
                    <dl>
                        <dd><input type="text" id="searchField" size="20" name="searchField" /></dd>
                        <dd><input type="submit" id="searchBtn" name="searchBtn" value="Zoek account" /></dd>
                    </dl>
                </form>
            </div>
        </div>
        
        
        
    </div>
    
    <div id="content">
        
        <h2>Nieuwe account toevoegen</h2>
        
        <form action="#" method="post" id="formAddAccount">
            <dl>
                <dt><label for="txtFirstName">Voornaam:</label></dt>
                <dd><input type="text" id="txtFirstName" name="txtFirstName" /></dd>
                <dt><label for="txtName">Naam:</label></dt>
                <dd><input type="text" id="txtName" name="txtName" /></dd>
                <dt><label for="cbActive"></label></dt>
                <dd><input type="checkbox" id="cbActive" name="cbActive" /></dd>
                <dt><label for="txtActiveUntill">Actief tot:</label></dt>
                <dd><input type="text" id="txtActiveUntill" name="txtActiveUntill" /></dd>
                <dt><label for="txtActiveFrom">Actief vanaf:</label></dt>
                <dd><input type="text" id="txtActiveFrom" name="txtActiveFrom" /></dd>
                <dt><label for="radioGender">Geslacht:</label></dt>
                <dd>
                    <input type="radio" id="radioGenderMale" name="radioGender" value="M" />
                    <label for="radioGenderMale">Man</label>
                    <input type="radio" id="radioGenderFemale" name="radioGender" value="V" />
                    <label for="radioGenderFemale">Vrouw</label>
                </dd>
                <dt><label for="txtActiveFrom">Actief vanaf:</label></dt>
                <dd><input type="text" id="txtActiveFrom" name="txtActiveFrom" /></dd>
                <dt><label for="txtActiveFrom">Actief vanaf:</label></dt>
                <dd><input type="text" id="txtActiveFrom" name="txtActiveFrom" /></dd>
                
                    
                    
<!--           
            `first_name`,
            `name`,
            `gender`,
            `birth_date`,
            `birth_place`,
            `nationality`,
            `street`,
            `house_number`,
            `post_code`,
            `city`,
            `country`,
            `email`,
            `phone`,
            `phone2`,
            `mobile`,
            `made_on`,
            `group_id`,
            `other_information`,
            `deleted`,
            `student_previous_school`,
            `student_stamnr`,
            `parent_occupation`-->
            
        </form>
        
        
    </div>
    
    <div id="footer">
        <p>footer 2012</p>
    </div>
    
</div>