<title>Solid Eagle</title>

<link rel="stylesheet" type="text/css" media="screen" href="../css/reset.css" />
<link rel="stylesheet" type="text/css" media="screen" href="../css/screen.css" />
<div id="wrapper">

    <div id="header">

        <h1>Centraal gebruikersbeheer DBZ</h1>
        
        <div id="loggedInAs">
            <p>Welkom, voornaam.naam <a href="#">logout</a></p>
        </div>
        
        <div id="menu">
            <ul>
                <li><a href="#">home</a></li>
                <li><a href="#">beheer accounts</a></li>
                <li><a href="#">configuratie</a></li>
            </ul>
            <div id="search">
                <form action="#" method="post" id="searchAccounts">
                    <dl>
                        <dd><input type="text" id="searchField" size="20" name="searchField" /></dd>
                        <dd><input type="submit" id="searchBtn" name="searchBtn" value="Zoek account" /></dd>
                    </dl>
                </form>
            </div>
        </div>
        
        
        
    </div>
    
    <div id="content">
        
    </div>
    
    <div id="footer">
        <p>footer 2012</p>
    </div>
    
</div>