<?php 
use solideagle\utilities\SuperEntities;

?>

<script>
	$(function(){
            
                var selectedArr = new Array();
              
                <?php if(!$this->manageTemplate)
                {?>
                    $(".selectUser:checked").each( 
                        function(k,v) { 
                            selectedArr.push($(v).attr("value"));
                        } 
                    );
                <?php
                }?>

		if(selectedArr.length > 0)
		{
                        $('#myModal').modal('show');

                        $("#deleteadsure").hide();
                        $("#deletesssure").hide();
                        $("#deletegappsure").hide();

                        $("#blnDeleteAd").click(function(){
                                $("#deleteadsure").toggle();
                                $("#blnDeleteAdSure").removeAttr("checked");
                        });
                        $("#blnAdMultipleEnableDisable").click(function(){
                                $("#radioAdEnableAccounts").toggle();
                                $("#radioAdDisableAccounts").toggle();
                                $("#optionAdMultipleEnable").removeAttr("checked");
                                $("#optionAdMultipleDisable").removeAttr("checked");
                        });
                        $("#blnDeleteSs").click(function(){
                                $("#deletesssure").toggle();
                                $("#blnDeleteSsSure").removeAttr("checked");
                        });
                        $("#blnDeleteGapp").click(function(){
                                $("#deletegappsure").toggle();
                                $("#blnDeleteGappSure").removeAttr("checked");
                        });
		}
                else
                {
                        // manage templates
                        <?php if($this->manageTemplate)
                        {?>
                                $('#myModal').modal('show');
                                $("#deleteadsure").hide();
                                $("#deletesssure").hide();
                                $("#deletegappsure").hide();
                        <?php
                        }else
                        {?>
                            alert("Geen gebruikers geselecteerd");
                        <?php
                        }?>

		}
	
		$("#formTasks").ajaxForm({
			data:  {"users":selectedArr},
			success: function(responseText, statusText, xhr, $form) { 

				if(responseText.length > 0)
				{
					alert(responseText);
				}else{
					$('#myModal').modal('hide');
					updateTree();
				}
				
	    } });

		
	});

</script>

<form
	class="form-horizontal"
	action="<?php echo $this->SE_path . "/usertasks/posttasks" ?>"
	method="post"
	id="formTasks">

	<div
		class="hide SEsupermodal"
		id="myModal">
		<div>
			<div class="modal-header">
				<a
					class="close"
					data-dismiss="modal">×</a>
                                <?php if($this->manageTemplate)
                                {?>
                                    <h3 id="modaltitle">Beheer taak templates</h3>
                                <?php
                                }else
                                {?>
                                    <h3 id="modaltitle">Taken uitvoeren</h3>
                                <?php
                                }?>
			</div>
			<div class="modal-body">

                            <?php if($this->manageTemplate)
                            {?>
                                <section id="tasktemplate">
                                    <div class="page-header">
                                        <h1>
                                            Taken templates
                                        </h1>
                                    </div>
                                    
                                    <div class="control-group">
                                        <label class="control-label" for="txtName">Naam template</label>
                                        <div class="controls">
                                                <input id="txtName" name="txtName" class="input-xlarge" type="text" value="<?php echo $this->template != null ? $this->template->getTemplateName() : "" ?>">
                                        </div>
                                    </div>
                                        
                                    
                                </section>
                            <?php
                            }?>
                            
				<section id="activedirectory">
					<div class="page-header">
						<h1>
							Active directory <small>taken</small>
						</h1>
					</div>

					<div class="row">
						<div class="span12">
 
                                                    <?php if ($this->multipleAccountsSelected || !$this->hasAdAccount || $this->manageTemplate)
                                                    {?>
                                                            <label class="checkbox">
                                                                    <input
                                                                            name="createAdAccount" id="createAdAccount" type="checkbox" <?php echo $this->config['createAdAccount'] != null ? ("checked=" . $this->config['createAdAccount']) : "" ?>>
                                                                    Account maken
                                                            </label>
                                                    <?php 
                                                    }if ($this->multipleAccountsSelected || $this->hasAdAccount || $this->manageTemplate)
                                                    {?>
                                                            <label class="checkbox">
                                                                Account verwijderen
                                                                <input name="deleteAdAccount" id="blnDeleteAd" type="checkbox" value="false" <?php echo $this->config['deleteAdAccount'] != null ? ("checked=" . $this->config['deleteAdAccount']) : "" ?>>
                                                            </label>
                                                            <div class="control-group error" id="deleteadsure">
                                                                <label class="checkbox error" id="lbldeleteadsure">
                                                                        Ja, ik ben zeker
                                                                        <input id="blndeleteadsure" name="deleteAdAccountSure" type="checkbox" value="false">
                                                                </label>  
                                                            </div>
                                                    <?php
                                                    }if ($this->multipleAccountsSelected || $this->hasAdAccountEnabled || $this->manageTemplate)
                                                    {?>
                                                            <label class="checkbox">
                                                                    Account deactiveren
                                                                    <input name="blnAdDisable" id="blnAdDisable" type="checkbox" <?php echo $this->config['blnAdDisable'] != null ? ("checked=" . $this->config['blnAdDisable']) : "" ?>>
                                                            </label>
                                                    <?php
                                                    }if($this->multipleAccountsSelected || !$this->hasAdAccountEnabled || $this->manageTemplate)
                                                    {?>
                                                            <label class="checkbox">
                                                                    Account activeren
                                                                    <input name="blnAdEnable" id="blnAdEnable" type="checkbox" <?php echo $this->config['blnAdEnable'] != null ? ("checked=" . $this->config['blnAdEnable']) : "" ?>>
                                                            </label>
                                                    <?php
                                                    }?>
                                                    
                                                        <label class="checkbox">
                                                                <input
                                                                        name="createAdHomedir"
                                                                        type="checkbox"
                                                                        data-toggle="collapse"
                                                                        data-target="#adHomeDirParams"
                                                                        value="true"
                                                                        <?php echo $this->config['createAdHomedir'] != null ? ("checked=" . $this->config['createAdHomedir']) : "" ?>>
                                                                Homedir maken
                                                        </label>

							<div
								id="adHomeDirParams"
								class="collapse out">
								<fieldset>
									<legend>Homefolder</legend>

									<div class="control-group">
										<label
											class="control-label"
											for="server">Server</label>
										<div class="controls">
											<input
												id="server"
												name="HomefolderServer"
												class="input-xlarge"
												type="text"
												value="<?php echo $this->config['HomefolderServer'] != null ? $this->config['HomefolderServer'] : SuperEntities::encode($this->defaults->server); ?>">
											<p class="help-block ">
												<i>server.domain.example</i>
											</p>
										</div>
									</div>

									<div class="control-group">
										<label
											class="control-label"
											for="serverpath">Homefolder pad op server</label>
										<div class="controls">
											<div class="input-append">
												<input
													id="serverpath"
													name="HomefolderPath"
													class="input-xlarge"
													type="text"
													value="<?php echo $this->config['HomefolderPath'] != null ? $this->config['HomefolderPath'] : SuperEntities::encode($this->defaults->serverpath); ?>"
													><span class="add-on">\janssensj</span>
												<p class="help-block ">
													<i>c:\pad\naar\homefolders</i>
												</p>
											</div>
										</div>
									</div>

									<div class="control-group">
										<label
											class="control-label"
											for="scanpath">Scanpad op server</label>
										<div class="controls">
											<input
												id="scanpath"
												name="ScanSharePath"
												class="input-xlarge"
												type="text"
												value="<?php echo $this->config['ScanSharePath'] != null ? $this->config['ScanSharePath'] : SuperEntities::encode($this->defaults->scanpath); ?>">
											<p class="help-block ">
												<i>c:\pad\naar\scanshare</i>
											</p>
										</div>
									</div>

									<div class="control-group">
										<label
											class="control-label"
											for="wwwpath">WWW pad op server</label>
										<div class="controls">
											<input
												id="wwwpath"
												name="WWWSharePath"
												class="input-xlarge"
												type="text"
												value="<?php echo $this->config['WWWSharePath'] != null ? $this->config['WWWSharePath'] : SuperEntities::encode($this->defaults->wwwpath); ?>">
											<p class="help-block ">
												<i>c:\pad\naar\wwwshare</i>
											</p>
										</div>
									</div>

								</fieldset>

							</div>
							
							<label class="checkbox">
								<input
									name="createUpDownFolders"
									type="checkbox"
									data-toggle="collapse"
									data-target="#adUpDownParams"
									value="true"
                                                                        <?php echo $this->config['createUpDownFolders'] != null ? ("checked=" . $this->config['createUpDownFolders']) : "" ?>>
								Upload &amp; Downloadfolders maken
							</label>

							<div
								id="adUpDownParams"
								class="collapse out">
								<fieldset>
									<legend>Upload & Downloadfolders</legend>

									<div class="control-group">
										<label
											class="control-label"
											for="server">Uploadpad</label>
										<div class="controls">
											<input
												id="server"
												name="UploadSharePath"
												class="input-xlarge"
												type="text"
												value="<?php echo $this->config['UploadSharePath'] != null ? $this->config['UploadSharePath'] : SuperEntities::encode($this->defaults->uploadpath); ?>">
											<p class="help-block ">
												<i>c:\pad\naar\upload</i>
											</p>
										</div>
										
											<label
											class="control-label"
											for="server">Downloadpad</label>
										<div class="controls">
											<input
												id="server"
												name="DownloadSharePath"
												class="input-xlarge"
												type="text"
												value="<?php echo $this->config['DownloadSharePath'] != null ? $this->config['DownloadSharePath'] : SuperEntities::encode($this->defaults->downloadpath); ?>">
											<p class="help-block ">
												<i>c:\pad\naar\download</i>
											</p>
										</div>

									</div>

								</fieldset>

							</div>

							<label class="checkbox">
								<input
									name="blnMoveHomeDir"
									type="checkbox"
									value=""
                                                                        <?php echo $this->config['createAdHomedir'] != null ? ("checked=" . $this->config['createAdHomedir']) : "" ?>>
								Homedir verplaatsen
							</label>

						</div>
					</div>
				</section>

				<section id="smartschool">
					<div class="page-header">
						<h1>
							Smartschool <small>taken</small>
						</h1>
					</div>

					<div class="row">
						<div class="span12">
                                                    
                                                    <?php if ($this->multipleAccountsSelected || !$this->hasSsAccount || $this->manageTemplate)
                                                    {?>
                                                            <label class="checkbox">
                                                                    <input
                                                                            name="createSsAccount"
                                                                            type="checkbox"
                                                                            value="true"
                                                                            <?php echo $this->config['createSsAccount'] != null ? ("checked=" . $this->config['createSsAccount']) : "" ?>>
                                                                    Account maken
                                                            </label>
                                                    <?php 
                                                    }if ($this->multipleAccountsSelected || $this->hasSsAccount || $this->manageTemplate)
                                                    {?>
                                                            <label class="checkbox">
                                                                Account verwijderen
                                                                <input name="deleteSsAccount" id="blnDeleteSs" type="checkbox" value="false"
                                                                    <?php echo $this->config['deleteSsAccount'] != null ? ("checked=" . $this->config['deleteSsAccount']) : "" ?>>
                                                            </label>
                                                            <div class="control-group error" id="deletesssure">
                                                                <label class="checkbox error" id="lbldeletesssure">
                                                                        Ja, ik ben zeker
                                                                        <input id="blndeletesssure" name="deleteSsAccountSure" type="checkbox" value="false">
                                                                </label>  
                                                            </div>
                                                    <?php
                                                    }if ($this->multipleAccountsSelected || $this->hasSsAccountEnabled || $this->manageTemplate)
                                                    {?>
                                                            <label class="checkbox">
                                                                    Account deactiveren
                                                                    <input name="blnSsDisable" id="blnSsDisable" type="checkbox" 
                                                                           <?php echo $this->config['blnSsDisable'] != null ? ("checked=" . $this->config['blnSsDisable']) : "" ?>>
                                                            </label>
                                                    <?php
                                                    }if($this->multipleAccountsSelected || !$this->hasSsAccountEnabled || $this->manageTemplate)
                                                    {?>
                                                            <label class="checkbox">
                                                                    Account activeren
                                                                    <input name="blnSsEnable" id="blnSsEnable" type="checkbox" 
                                                                           <?php echo $this->config['blnSsEnable'] != null ? ("checked=" . $this->config['blnSsEnable']) : "" ?>>
                                                            </label>
                                                    <?php
                                                    }?>
    
						</div>
					</div>
				</section>

				<section id="googleapps">
					<div class="page-header">
						<h1>
							Google <small>taken</small>
						</h1>
					</div>

					<div class="row">
                                            <div class="span12">
                                                <?php if ($this->multipleAccountsSelected || !$this->hasGappAccount || $this->manageTemplate)
                                                {?>
                                                    <label class="checkbox">
                                                            <input
                                                                    name="createGappAccount"
                                                                    type="checkbox"
                                                                    value="true" 
                                                                    <?php echo $this->config['createGappAccount'] != null ? ("checked=" . $this->config['createGappAccount']) : "" ?>>
                                                            Account maken
                                                    </label>
                                                <?php 
                                                }if ($this->multipleAccountsSelected || $this->hasGappAccount || $this->manageTemplate)
                                                {?>
                                                    <label class="checkbox">
                                                        Account verwijderen
                                                        <input name="deleteGappAccount" id="blnDeleteGapp" type="checkbox" value="false" 
                                                               <?php echo $this->config['deleteGappAccount'] != null ? ("checked=" . $this->config['deleteGappAccount']) : "" ?>>
                                                    </label>
                                                    <div class="control-group error" id="deletegappsure">
                                                        <label class="checkbox error" id="lbldeletegappsure">
                                                                Ja, ik ben zeker
                                                                <input id="blndeletegappsure" name="deleteGappAccountSure" type="checkbox" value="false" >
                                                        </label>  
                                                    </div>
                                                <?php
                                                }if ($this->multipleAccountsSelected || $this->hasGappAccountEnabled || $this->manageTemplate)
                                                {?>
                                                    <label class="checkbox">
                                                            Account deactiveren
                                                            <input name="blnGappDisable" id="blnGappDisable" type="checkbox" 
                                                                   <?php echo $this->config['blnGappDisable'] != null ? ("checked=" . $this->config['blnGappDisable']) : "" ?>>
                                                    </label>
                                                <?php
                                                }if($this->multipleAccountsSelected || !$this->hasGappAccountEnabled || $this->manageTemplate)
                                                {?>
                                                    <label class="checkbox">
                                                            Account activeren
                                                            <input name="blnGappEnable" id="blnGappEnable" type="checkbox" 
                                                                   <?php echo $this->config['blnGappEnable'] != null ? ("checked=" . $this->config['blnGappEnable']) : "" ?>>
                                                    </label>
                                                <?php
                                                }?>

                                            </div>
					</div>
				</section>

			</div>
			<div class="modal-footer">
				<a
					href="#"
					class="btn"
					data-dismiss="modal">Annuleren</a>
				<button class="btn btn-primary" id="submitBtn" name="submitBtn" type="submit" value="<?php 
                                            if($this->manageTemplate)
                                                echo ($this->addtemplate) ? "addTemplate" : "editTemplate";
                                            else
                                                echo "addTasks"
                                        ?>">Uitvoeren</button>
			</div>
		</div>
	</div>
    
 </form>
