


<form class="form-horizontal"
	action="<?php echo $this->SE_path . "/usertasks/posttasks" ?>"
	method="post" id="formAddUser">
	<fieldset>
		<legend>Homefolder</legend>

		<div class="control-group">
			<label class="control-label" for="server">Server</label>
			<div class="controls">
				<input id="server" name="server" class="input-xlarge" type="text"
					value="<?php echo $this->defaults->server; ?>">
					<p class="help-block "><i>server.domain.example</i></p>
			</div>
			
		</div>
		
		<div class="control-group">
			<label class="control-label" for="serverpath">Homefolder pad op server</label>
			<div class="controls">
				<input id="serverpath" name="serverpath" class="input-xlarge" type="text"
					value="<?php echo $this->defaults->serverpath; ?>"> \<?php echo $this->person->getAccountUsername(); ?>
					<p class="help-block "><i>c:\pad\naar\homefolders</i></p>
			</div>
		</div>

		<div class="control-group">
			<label class="control-label" for="scanpath">Scanpad op server</label>
			<div class="controls">
				<input id="scanpath" name="scanpath" class="input-xlarge" type="text"
					value="<?php echo $this->defaults->scanpath; ?>">
					<p class="help-block "><i>c:\pad\naar\scanshare</i></p>
			</div>
		</div>
		
				<div class="control-group">
			<label class="control-label" for="wwwpath">WWW pad op server</label>
			<div class="controls">
				<input id="wwwpath" name="wwwpath" class="input-xlarge" type="text"
					value="<?php echo $this->defaults->wwwpath; ?>">
					<p class="help-block "><i>c:\pad\naar\wwwshare</i></p>
			</div>
		</div>

		<?php //if user.type contains leerkracht ?>
		<div class="control-group">
			<label class="control-label" for="downloadpath">Download pad op server</label>
			<div class="controls">
				<input id="downloadpath" name="downloadpath" class="input-xlarge" type="text"
					value="<?php echo $this->defaults->downloadpath; ?>">
					<p class="help-block "><i>c:\pad\naar\downloadshare</i></p>
			</div>
		</div>
		
		<div class="control-group">
			<label class="control-label" for="uploadpath">Upload pad op server</label>
			<div class="controls">
				<input id="uploadpath" name="uploadpath" class="input-xlarge" type="text"
					value="<?php echo $this->defaults->uploadpath; ?>">
					<p class="help-block "><i>c:\pad\naar\uploadshare</i></p>
			</div>
		</div>
		<?php ?>
	
	
	<input type="hidden" name="personid" value="<?php echo $this->person->getId(); ?>">
	
	<div class="form-actions">
		<button class="btn btn-primary" type="submit">Maken</button>
		
		</div>
		
	
	</fieldset>
		
</form>