<script>
	$(function(){

	

		$("#formAddUser").ajaxForm({
			success: function(responseText, statusText, xhr, $form) { 

				if(responseText.length > 0)
				{
					alert(responseText);
				}else{
					showUsers();
					updateTree();
				}
	    } });
		
	});

</script>


<form class="form-horizontal"
	action="<?php echo $this->SE_path . "/users/adduserpost" ?>"
	method="post" id="formAddUser">
	<fieldset>
		<legend>Gebruiker maken</legend>

		<div class="control-group">
			<label class="control-label" for="txtFirstName">Voornaam</label>
			<div class="controls">
				<input id="txtFirstName" name="txtFirstName" class="input-xlarge" type="text"
					value="">
			</div>
		</div>
		
		<div class="control-group">
			<label class="control-label" for="txtName">Naam</label>
			<div class="controls">
				<input id="txtName" name="txtName" class="input-xlarge" type="text"
					value="">
			</div>
		</div>

		


		<div class="form-actions">
		<button class="btn btn-primary" type="submit">Opslaan</button>
		
		</div>
		
		<input type="hidden" name="groupid" value="<?php echo $this->group->getId(); ?>">
	</fieldset>
</form>
