<script>

	var selectedGroupId = -1;

	$(function(){
		updateTree();


		

		$("#ShowUsersLink").click(function(){
			showUsers();
		});

		$("#EditGroupLink").click(function(){

			/*$("#myModal .modal-body").load("<?php echo $this->SE_path . '/groups/editgroup?gid=' ?>" + selectedGroupId);

			$("#modaltitle").html("Groep bewerken");
			
			$('#myModal').modal('show');*/

			$("#groepcontent").load("<?php echo $this->SE_path . '/groups/editgroup?gid=' ?>" + selectedGroupId);
		
			
		});

		$("#CreateSubGroupLink").click(function(){

			$("#groepcontent").load("<?php echo $this->SE_path . '/groups/addsubgroup?gid=' ?>" + selectedGroupId);
			
		});

		$("#CreateUserLink").click(function(){

			$("#groepcontent").load("<?php echo $this->SE_path . '/users/adduser?gid=' ?>" + selectedGroupId);
			
		});
		
		
		showUsers();
	});

	function updateTree()
	{
		$("#grouptree").jstree({ 
			"ui" : {	
				"initially_select" : [ "tree75" ]
			},
			"json_data" : {
				"ajax" : {
					"url" : "groups/getgroup",
					"data" : function (n) { 
						return { id : n.attr ? n.attr("id") : 0 }; 
					},
					"progressive_render" : true,
					"progressive_unload" : true
				}
			},
			"plugins" : [ "themes", "json_data","ui" ]
		}).bind("select_node.jstree", function (event, data) { 
			selectedGroupId = data.rslt.obj.attr("groupid");

			groupname =  data.rslt.obj.attr("groupname");

			$("#groupname").html(groupname);

			showUsers();

			if($("#userstable").length)
			{
				$("#userstable").dataTable().fnReloadAjax('users/getusers?gid='+selectedGroupId);
			}
			
		});
	}


	function showUsers()
	{
		$("#groepcontent").html("");

		$("<table id='userstable' class='table'>").append("<thead>\
				<tr>\
				<td>ID</td>\
				<td>Voornaam</td>\
				<td>Achternaam</td>\
				<td>Gebruikersnaam</td>\
				<td>Actief</td>\
				<td>Gemaakt op</td>\
			</tr>\
		</thead>").appendTo($("#groepcontent"));


		$("#userstable").dataTable({
			"bSort":true,
			"aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
			  "sDom": '<"row-fluid"fl><"row-fluid"<"btn-group span6"p><"span6"i>>rt',//'<"row-fluid well"fl><"row-fluid well btn-group"<"span6"p><"span6"i>>rt',
	        "bProcessing": true,
	        "oLanguage": {
	            "sProcessing": "Data ophalen...",
	            "sLengthMenu": "Aantal resultaten per pagina: _MENU_ ",
	            "sZeroRecords": "Geen resultaten gevonden",
	            "sInfo": "_START_ tot _END_ van _TOTAL_ resultaten",
	            "sInfoEmpty": "Geen resultaten om weer te geven",
	            "sInfoFiltered": " (gefilterd uit _MAX_ resultaten)",
	            "sInfoPostFix": "",
	            "sSearch": "Zoeken:",
	            "sEmptyTable": "Geen resultaten aanwezig in de tabel",
	            "sInfoThousands": ".",
	            "sLoadingRecords": "Een moment geduld aub - bezig met laden...",
	            "oPaginate": {
	                "sFirst": "Eerste",
	                "sLast": "Laatste",
	                "sNext": "Volgende",
	                "sPrevious": "Vorige"
	            }
	        },
	       // "sAjaxSource": 'users/getusers'
	    } );
		
	}

	
	
	
</script>

<?php //modal hide fade ?>

<div class="hide SEsupermodal" id="myModal">
<div>
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3 id="modaltitle"></h3>
	</div>
	<div class="modal-body">
		<p>One fine body…</p>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Annuleren</a> <a href="#" class="btn btn-primary">Opslaan</a>
	</div>
	</div>
</div>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span3">
			<h1>Groepen</h1>

			<div id="grouptree">
				<!-- tree will be rendered here -->
			</div>
		</div>
		<div class="span9">

			<ul class="nav nav-pills ">
				<li><h2 style="line-height: 30px">
						Groep <span id="groupname"></span>
					</h2></li>
				<li class="dropdown" id="menu1"><a class="dropdown-toggle"
					data-toggle="dropdown" href="#menu1"> Acties <b class="caret"></b>
				</a>
					<ul class="dropdown-menu">
						  <li><a id="ShowUsersLink" href="#"><i class="icon-th-list"></i> Gebruikers
								tonen</a></li>
						<li><a id="EditGroupLink" href="#"><i class="icon-pencil"></i>
								Groep bewerken</a></li>
						<li><a id="CreateSubGroupLink" href="#"><i class="icon-plus"></i>
								Subgroep maken</a></li>
						<li><a id="CreateUserLink" href="#"><i class="icon-user"></i>
								Gebruiker maken</a></li>
						<li class="divider"></li>
						<li><a href="#"><i class="icon-list-alt"></i> Multitask</a></li>
					</ul>
				</li>



			</ul>

			<div id="groepcontent"></div>

		</div>
	</div>
</div>


