



<script>

	var selectedGroupId = -1;

	$(function(){
		updateTree();


		$("#ShowUsersLink").click(function(){
			showUsers();
		});

		$("#EditGroupLink").click(function(){
			
			$("#groepcontent").load("<?php echo $this->SE_path . '/groups/editgroup?gid=' ?>" + selectedGroupId);
		});

		$("#CreateSubGroupLink").click(function(){

			$("#groepcontent").load("<?php echo $this->SE_path . '/groups/addsubgroup?gid=' ?>" + selectedGroupId);
		});

		$("#CreateUserLink").click(function(){

			$("#groepcontent").load("<?php echo $this->SE_path . '/users/adduser?gid=' ?>" + selectedGroupId);
		});
		
		
		showUsers();
	});

	function updateTree()
	{
		$("#grouptree").jstree({ 
			"ui" : {	
				"initially_select" : [ "tree75" ]
			},
			"json_data" : {
				"ajax" : {
					"url" : "users/getgroup",
					"data" : function (n) { 
						return { id : n.attr ? n.attr("id") : 0 }; 
					},
					"progressive_render" : true,
					"progressive_unload" : true
				}
			},
			"plugins" : [ "themes", "json_data","ui" ]
		}).bind("select_node.jstree", function (event, data) { 
			selectedGroupId = data.rslt.obj.attr("groupid");

			groupname =  data.rslt.obj.attr("groupname");

			$("#groupname").html(groupname);

			if($("#userstable").length)
			{
				$("#userstable").dataTable().fnReloadAjax('users/getusers?gid='+selectedGroupId);
			}
			
		});
	}


	function showUsers()
	{
		$("#groepcontent").html("<h2>Gebruikers</h2>");

		$("<table id='userstable' class='table'>").append("<thead>\
				<tr>\
				<td>ID</td>\
				<td>Voornaam</td>\
				<td>Achternaam</td>\
				<td>Gebruikersnaam</td>\
				<td>Actief</td>\
				<td>Gemaakt op</td>\
			</tr>\
		</thead>").appendTo($("#groepcontent"));


		$("#userstable").dataTable({
			"bSort":true,
			"aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
			  "sDom": '<"row-fluid"fl><"row-fluid"<"btn-group span6"p><"span6"i>>rt',//'<"row-fluid well"fl><"row-fluid well btn-group"<"span6"p><"span6"i>>rt',
	        "bProcessing": true,
	        "oLanguage": {
	            "sProcessing": "Data ophalen...",
	            "sLengthMenu": "Aantal resultaten per pagina: _MENU_ ",
	            "sZeroRecords": "Geen resultaten gevonden",
	            "sInfo": "_START_ tot _END_ van _TOTAL_ resultaten",
	            "sInfoEmpty": "Geen resultaten om weer te geven",
	            "sInfoFiltered": " (gefilterd uit _MAX_ resultaten)",
	            "sInfoPostFix": "",
	            "sSearch": "Zoeken:",
	            "sEmptyTable": "Geen resultaten aanwezig in de tabel",
	            "sInfoThousands": ".",
	            "sLoadingRecords": "Een moment geduld aub - bezig met laden...",
	            "oPaginate": {
	                "sFirst": "Eerste",
	                "sLast": "Laatste",
	                "sNext": "Volgende",
	                "sPrevious": "Vorige"
	            }
	        },
	       // "sAjaxSource": 'users/getusers'
	    } );
		
	}
	
</script>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span2">
			<h1>Groepen</h1>

			<div id="grouptree">
				<!-- tree will be rendered here -->
			</div>
		</div>
		<div class="span10">

			<ul class="nav nav-pills ">
				<li><h2  style="line-height: 30px"><span id="groupname"></span> <small>Groep opties</small></h2></li>
				<li><a id="ShowUsersLink" href="#"><i class="icon-th-list"></i>Gebruikers
						tonen</a></li>
				<li><a id="EditGroupLink" href="#"><i class="icon-pencil"></i>Groep
						bewerken</a></li>
				<li><a id="CreateSubGroupLink" href="#"><i class="icon-plus"></i>Subgroep
						maken</a></li>
				<li><a id="CreateUserLink" href="#"><i class="icon-user"></i>Gebruiker
						maken</a></li>
			</ul>

			<div id="groepcontent">
				

				
			</div>

		</div>
	</div>
</div>


