<script>
	$(function(){

                var selectedArr = new Array();
                
                $(".selectUser:checked").each( 
                        function(k,v) { 
                            selectedArr.push($(v).attr("value"));
                        } 
                );
                
                if(selectedArr.length > 0)
		{
                    $('#moveModal').modal('show');
                    updateMiniTree();
                }
                else
                {
                    alert("Geen gebruikers geselecteerd");
                }   

                $("#formMoveUser").ajaxForm({
                        data:  {"users":selectedArr},
                        success: function(responseText, statusText, xhr, $form) { 

                                if(responseText.length > 0)
                                {
                                        alert(responseText);
                                }else{
                                        $('#moveModal').modal('hide');
                                        updateTree();
                                }

                } });
                
                
                
		
	});
        
        function updateMiniTree()
        {
                $("#groupminitree").jstree({ 
                        "ui" : {	
                                "initially_select" : [ "tree"+selectedGroupId ]
                        },
                        "json_data" : {
                                "ajax" : {
                                        "url" : "<?php echo $this->SE_path . '/groups/getgroup' ?>",
                                        "data" : function (n) { 
                                                return { id : n.attr ? n.attr("id") : 0 }; 
                                        },
                                        "progressive_render" : true,
                                        "progressive_unload" : true
                                }
                        },
                        "plugins" : [ "themes", "json_data","ui" ]
                }).bind("select_node.jstree", function (event, data) { 
                        selectedGroupId = data.rslt.obj.attr("groupid");
                        $("#newgid").val(selectedGroupId);
                });

        }

</script>

<form class="form-horizontal" action="<?php echo $this->SE_path . "/users/movepost" ?>" method="post" id="formMoveUser">

	<div class="hide SEsupermodal" id="moveModal">
		<div>
			<div class="modal-header">
				<a class="close" data-dismiss="modal">×</a>
				<h3 id="modaltitle">
                                    Verplaats <?php echo $this->displayName; ?> naar 
				</h3>
			</div>
			<div class="modal-body" style="width: 300px;">
                                <fieldset>
                                    <input type="hidden" id="newgid" name="newgid">
                                    <input type="hidden" id="oldgid" name="oldgid" value="<?php echo $this->oldgid; ?>">
                                    <div id="groupminitree">
                                            <!-- tree will be rendered here -->
                                    </div>
					
				</fieldset>
			</div>
			<div class="modal-footer">
                            <a href="#" class="btn" data-dismiss="modal">Annuleren</a>
                            <button class="btn btn-primary" name="submit" value="move" type="submit">Verplaatsen</button>
			</div>
		</div>
	</div>

</form>
