<script>
	$(function(){

		

		$("#formAddGroup").ajaxForm({
			success: function(responseText, statusText, xhr, $form) { 

				if(responseText.length > 0)
				{
					alert(responseText);
				}else{
					showUsers();
					updateTree();
				}
				
	    } });
		
	});

</script>


<form class="form-horizontal"
	action="<?php echo $this->SE_path . "/groups/updategrouppost" ?>"
	method="post" id="formAddGroup">
	<fieldset>
		<legend>Subgroep maken</legend>

		<div class="control-group">
			<label class="control-label" for="txtName">Naam</label>
			<div class="controls">
				<input id="txtName" class="input-xlarge" type="text"
					value="">
			</div>
		</div>

		<div class="control-group">
			<label class="control-label" for="txtDescription">Omschrijving</label>
			<div class="controls">
				<textarea id="txtDescription" class="input-xlarge" rows="3"></textarea>
			</div>
		</div>
		


		<div class="form-actions">
		<button class="btn btn-primary" type="submit">Opslaan</button>
		
		</div>
		
		<input type="hidden" id="groupid" value="<?php echo $this->groupid ?>">
	</fieldset>
</form>
