
<?php use solideagle\utilities\SuperEntities; ?>

<script>
	$(function(){

		$("#lbldeletesure").hide();

		$("#blnDelete").click(function(){
			$("#lbldeletesure").toggle();
			$("#blnDeleteSure").removeAttr("checked");
		});
		
		$("#formEditGroup").ajaxForm({
			success: function(responseText, statusText, xhr, $form) { 

				if(responseText.length > 0)
				{
					alert(responseText);
				}else{
					showUsers();
					updateTree();
				}
				
	    } });
		
	});

</script>






<form class="form-horizontal"
	action="<?php echo $this->SE_path . "/groups/updategrouppost" ?>"
	method="post" id="formEditGroup">
	<fieldset>
		<legend>Groep bewerken</legend>

		<div class="control-group">
			<label class="control-label" for="txtName">Naam</label>
			<div class="controls">
				<input id="txtName" name="groupName" class="input-xlarge"
					type="text"
					value="<?php echo SuperEntities::encode($this->group->getName()); ?>">
			</div>
		</div>

		<div class="control-group">
			<label class="control-label" for="txtDescription">Omschrijving</label>
			<div class="controls">
				<textarea id="txtDescription" name="groupDescription"
					class="input-xlarge" rows="3"><?php echo SuperEntities::encode($this->group->getDescription()) ?></textarea>
			</div>
		</div>
		
		
		<div class="control-group">
			<label class="control-label" for="txtDescription">Verplaatsen</label>
			<div class="controls">
				<select name="selectGroup">
					<option value="ignore">Niet verplaatsen</option>
					<?php foreach($this->groups as $group)
					{
					
					?>
					
					<option value ="<?php echo $group->getId(); ?>"><?php echo SuperEntities::encode($group->getName()); ?></option>
						
					<?php } ?>
					
				</select>
			</div>
		</div>

		<div class="control-group error">
			<label class="control-label" for="blnDelete">Groep verwijderen</label>
			<div class="controls">
				<label class="checkbox"> <input id="blnDelete" name="delete"
					type="checkbox" value="delete"> Ja, ik wil deze groep verwijderen
				</label> <label id="lbldeletesure" class="checkbox"> <input
					id="blnDeleteSure" name="deletesure" type="checkbox" value="delete">
					Ja, ik ben zeker
				</label>
			</div>
		</div>

		<div class="form-actions">
			<button class="btn btn-primary" type="submit">Opslaan</button>

		</div>

		<input type="hidden" name="groupid"
			value="<?php echo $this->group->getId() ?>">
	</fieldset>
</form>
