<div>

	<div class="page-header">
		<h1>Klassen importeren en aanmaken</h1>
	</div>

	<form class="form-horizontal" enctype="multipart/form-data" method="post" >
		<fieldset>
		<legend>Stap 1: Upload bestand</legend>
			<div class="control-group">
				<label
					class="control-label"
					for="fileInput">Filemaker csv bestand:</label>
				<div class="controls">
					<input
						id="fileInput"
						class="input-file"
						name="csvfile"
						type="file">
				</div>
			</div>
			<div class="form-actions">
				<button
					class="btn btn-primary"
					type="submit" name="submit" value="true">Bestand laden</button>
			</div>
		</fieldset>
	</form>

</div>

