<div>

	<div class="page-header">
		<h1>Personen importeren en aanmaken</h1>
	</div>
    

        <form class="form-horizontal" enctype="multipart/form-data" method="post" >
                <fieldset>
                <legend>Stap 1: Upload CSV-bestand</legend>
                <div class="alert alert-error">

    <strong>Opgelet!</strong> Dit bestand moet opgeslaan zijn als UTF-8!
    </div>
                        <div class="control-group">
                                <label
                                        class="control-label"
                                        for="fileInput">CSV-bestand: </label>
                                <div class="controls">
                                        <input
                                                id="fileInput"
                                                class="input-file"
                                                name="csvfile"
                                                type="file">
                                </div>
                        </div>

                        <div class="form-actions">
                                <button
                                        class="btn btn-primary"
                                        type="submit" name="submit" value="true">Bestand laden</button>
                        </div>
                </fieldset>
        </form>
    
        <?php 
        if ($this->step2)
        {?>
    
            <div>
                <legend>Stap 2: Verifieer personen</legend>
                
                    <div class="alert alert-info">
                        <?php echo $this->logInfo; ?>
                    </div>
                        <table class="table table-striped">
                            <?php
                            foreach($this->data as $row)
                            {?>
                                <tr>
                            <?php foreach($row as $val)
                                {
                                ?>
                                    <td><?php echo $val; ?></td>
                                <?php
                                }
                                ?>
                                </tr>
                            <?php
                            }?>
                               
                        </table>
            </div>
    
        <?php }?>


</div>

