<?php use solideagle\utilities\SuperEntities;
?>


<div>

	<div class="page-header">
		<h1>Klassen importeren en aanmaken</h1>
	</div>

	<form
		class="form-horizontal"
		enctype="multipart/form-data"
		method="post">
		<fieldset>
			<legend>Stap 2: Bekijk veranderingen</legend>

			<h2>Leerlingen die aangemaakt worden</h2>
			<table class="table table-striped">
				<thead>
					<tr>
						<?php
						if(count($this->studentsImport->new) > 0)
						{
							$row = get_object_vars($this->studentsImport->new[0]);
							foreach($row as $key => $val)
							{
								echo "<td>" . $key . "</td>";
							}

						}
						?>
					</tr>
				</thead>
				<?php
				foreach($this->studentsImport->new as $row)
				{
					$row = get_object_vars($row)
					?>
				<tr>
					<?php foreach($row as $val)
					{
						?>
					<td><?php echo $val; ?></td>
					<?php
					}
					?>
				</tr>
				<?php
        }?>

			</table>

			<h2>Leerlingen die geupdate worden</h2>

			<table class="table table-striped">
				<thead>
					<tr>
						<?php
						if(count($this->studentsImport->updated) > 0)
						{
							$row = get_object_vars($this->studentsImport->updated[0]);
							foreach($row as $key => $val)
							{
								echo "<td>" . $key . "</td>";
							}

						}
						?>
					</tr>
				</thead>
				<?php
				foreach($this->studentsImport->updated as $row)
				{
					$row = get_object_vars($row)
					?>
				<tr>
					<?php foreach($row as $val)
					{
						?>
					<td><?php echo $val; ?></td>
					<?php
					}
					?>
				</tr>
				<?php
        }?>

			</table>

			<div class="form-actions ">
				<button
					class="btn btn-primary"
					type="submit"
					name="submit"
					value="true">Uitvoeren</button>
			</div>
		</fieldset>
	</form>

</div>



