

<div>

	<div class="page-header">
		<h1>Klassen importeren en aanmaken</h1>
	</div>

	<form
		class="form-horizontal"
		enctype="multipart/form-data"
		method="post">
		<fieldset>
			<legend>Stap 2: Kies klassen om aan te maken</legend>
			<div class="clearfix">
			<?php


			foreach($this->klassen as $klas)
			{
				?>
					
				<label
					class="control-label"
					for="checkbox">
					<?php echo $klas; ?>
				
					<input
						type="checkbox"
						checked="checked"
						name="klassen[]"
						value="<?php echo $klas; ?>"></label>
			<?php
			}

			?>
				</div>
			<div class="form-actions ">
				<button
					class="btn btn-primary"
					type="submit"
					name="submit"
					value="true">Klassen maken</button>
			</div>
		</fieldset>
	</form>

</div>



