<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Centraal gebruikersbeheer DBZ');

echo $this->doctype(); ?>
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<link rel="stylesheet" type="text/css" media="screen" href="../css/reset.css" />
<link rel="stylesheet" type="text/css" media="screen" href="../css/forms.css" />
<link rel="stylesheet" type="text/css" media="screen" href="../css/screen.css" />
</head>
<body>
    
<div id="wrapper">

    <div id="header">

        <h1>Centraal gebruikersbeheer DBZ</h1>

        <div id="menu">
            <ul>
                <li><a href="#">home</a></li>
                <li><a href="#">beheer</a></li>
                <li><a href="#">configuratie</a></li>
            </ul>
            <div id="search">
                <form action="#" method="post" id="searchAccounts">
                    <dl>
                        <dt><input type="text" id="searchField" size="20" name="searchField" /></dt>
                        <dd><input type="submit" id="searchBtn" name="searchBtn" value="Zoek account" /></dd>
                    </dl>
                </form>
            </div>
        </div>

        <div id="loggedInAs">
            <p>Welkom, voornaam.naam <a href="#">logout</a></p>
        </div>
        
    </div>

        <div id="content">
            <?php echo $this->layout()->content; ?>
        </div>

        <div id="footer">
            <p>footer 2012</p>
        </div>

</div>
        
</body>
</html>