<script>
	$(function(){
            
            $('#taskTemplateModal').modal('show');
            
            <?php foreach($this->taskTemplates as $taskTemplate)
            {?>
                    $("#btnEditTemplate<?php echo $taskTemplate->getTemplateName(); ?>").click(function(){ 
                        $('#taskTemplateModal').modal('hide');
                        $("#modalholder").load("<?php echo $this->SE_path . '/usertasks/getalltasksforuser' ?>", new makePostArray('<?php echo $taskTemplate->getTemplateName(); ?>'));
                    }); 
                    
                    $("#btnRemoveTemplate<?php echo $taskTemplate->getTemplateName(); ?>").click(function(){ 
                       var r = confirm("Verwijder takentemplate \"<?php echo $taskTemplate->getTemplateName(); ?>\"");
                       if (r==true)
                       {
                            
                       }
                    }); 
            <?php
            }?>
                    
            $("#btnNewTemplate").click(function(){ 
                $('#taskTemplateModal').modal('hide');
                $("#modalholder").load("<?php echo $this->SE_path . '/usertasks/getalltasksforuser?addtemplate=true' ?>");
            });    
            
            function makePostArray(jspost) {
		  		 this.jspost = jspost;
            }
            
            

	});

</script>

<div
	class="hide SEsupermodal"
	id="taskTemplateModal">
	<div>
		<div class="modal-header">
			<a
				class="close"
				data-dismiss="modal">×</a>
			<h3 id="modaltitle">Beheer taak templates</h3>
		</div>

		<div class="modal-body">

			<section id="tasktemplate">

				<div class="control-group">

					<h3>Bestaande takentemplates aanpassen</h3>

					<table>
				
					<?php if(isset($this->taskTemplates) )
					{
						foreach($this->taskTemplates as $taskTemplate)
                        {?>
					<tr><td><a
						href="#"
						id="btnEditTemplate<?php echo $taskTemplate->getTemplateName() ?>"
						name="btnEditTemplate<?php echo $taskTemplate->getTemplateName() ?>"
						class="btn btn-mini"><?php echo $taskTemplate->getTemplateName() ?> </a></td>
						 <td><a
						href="#"
						id="btnRemoveTemplate<?php echo $taskTemplate->getTemplateName() ?>"
						name="btnRemove<?php echo $taskTemplate->getTemplateName() ?>"
						class="btn btn-mini"><i class="icon-remove"></i> </a></td></tr>
					<?php
                        }
                        }?>
                        
                        	</table>

				</div>

				<div class="control-group">

					<a
						href="#"
						id="btnNewTemplate"
						name="btnNewTemplate"
						class="btn btn-primary">Maak nieuwe template</a>

				</div>

			</section>

		</div>


		<div class="modal-footer">
			<a
				href="#"
				class="btn"
				data-dismiss="modal">OK</a>
		</div>

	</div>
</div>
