<?php //echo $this->doctype() ?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Gebruikersbeheer</title>
<?php 

$this->headScript()->prependFile($this->SE_path . "/datatables/js/datatable.custom.solideagle.js");
$this->headScript()->prependFile($this->SE_path . "/datatables/js/jquery.dataTables.min.js");
$this->headScript()->prependFile($this->SE_path . "/js/jquery.easytabs.min.js");
$this->headScript()->prependFile($this->SE_path . "/js/jstree/jquery.jstree.js");
$this->headScript()->prependFile($this->SE_path . "/bootstrap/js/bootstrap.min.js");
$this->headScript()->prependFile($this->SE_path . "/js/jquery.form.js");
$this->headScript()->prependFile($this->SE_path . "/js/jquery-ui-1.8.18.custom.min.js");
$this->headScript()->prependFile($this->SE_path . "/js/jquery-1.7.1.min.js");

echo $this->headScript();

echo "\n";

$this->headLink()->appendStylesheet($this->SE_path.'/css/ui-custom/jquery-ui-1.8.18.custom.css') ;
$this->headLink()->appendStylesheet($this->SE_path.'/css/style.css') ;
$this->headLink()->appendStylesheet($this->SE_path.'/bootstrap/css/bootstrap.css');
//$this->headLink()->appendStylesheet($this->SE_path.'/bootstrap/css/bootstrap-responsive.css');


echo $this->headLink();

?>
</head>
<body>

	<div id="userbar">
		<span>Gebruikersnaam</span>
	</div>

	<div id="header">
		<span><a
			href="<?php echo $this->url(array('controller'=>'index','action'=>'index')) ?>">Gebruikersbeheer</a>
			
		</span><span class="label label-info" style="line-height: 75px;font-size:x-small;vertical-align:top;">Beta</span> <img
			src="<?php echo $this->serverUrl().$this->baseUrl(); ?>/images/logo.png"
			height="90px" />
	</div>

	<div id="content">
		<div id="nav-container">
			<div class="navbar">
				<div class="navbar-inner">
					<div class="container">
						<?php echo $this->navigation()->menu()->setOnlyActiveBranch(true)->setUlClass("nav")->setRenderParents(true)->setMinDepth(1)->setMaxDepth(1); ?>
					</div>
				</div>
			</div>

			<div class="navbar">
				<div class="navbar-inner subnav">
					<div class="container">
						<?php echo $this->navigation()->menu()->setOnlyActiveBranch(true)->setUlClass("nav")->setRenderParents(false)->setMinDepth(2)->setMaxDepth(2); ?>
					</div>
				</div>
			</div>
		</div>

		<div id="breadcrumbs"></div>

		<?php echo $this->layout()->content ?>

	</div>

</body>
</html>
