<?php //echo $this->doctype() ?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Zend Framework Quickstart Application</title>






<?php 



$this->headScript()->appendFile($this->SE_path . "/js/jquery-1.7.1.min.js");
$this->headScript()->appendFile($this->SE_path . "/js/jquery.form.js");
$this->headScript()->appendFile($this->SE_path . "/js/jquery.easytabs.min.js");
$this->headScript()->appendFile($this->SE_path . "/js/jstree/jquery.jstree.js");

$this->headScript()->appendFile($this->SE_path . "/bootstrap/js/bootstrap.min.js");

//echo $this->jQuery(); 

echo $this->headScript(); 

?>
<!--  <script>
$(function()
{
	$('#nav-container ul').attr("class","nav");

});

</script>-->

<?php

echo "\n";

$this->headLink()->appendStylesheet($this->SE_path.'/css/style.css') ;


$this->headLink()->appendStylesheet($this->SE_path.'/bootstrap/css/bootstrap.css');
$this->headLink()->appendStylesheet($this->SE_path.'/bootstrap/css/bootstrap-responsive.css');


echo $this->headLink();

?>

</head>
<body>

	<div id="userbar">
		<span>gebruikersnaam</span>
	</div>

	<div id="header">
		<span><a href="<?php echo $this->url(array('controller'=>'index','action'=>'index')) ?>">Gebruikersbeheer</a></span> <img
			src="<?php echo $this->serverUrl().$this->baseUrl(); ?>/images/logo.png"
			height="90px" />
	</div>

	<div id="content">
		<div id="nav-container">
			<div class="navbar">
				<div class="navbar-inner">
					<div class="container">
					<?php echo $this->navigation()->menu()->setOnlyActiveBranch(true)->setUlClass("nav")->setRenderParents(true)->setMinDepth(1)->setMaxDepth(1); ?>
					</div>
				</div>
			</div>

			<div class="navbar">
				<div class="navbar-inner">
					<div class="container">
					<?php echo $this->navigation()->menu()->setOnlyActiveBranch(true)->setUlClass("nav")->setRenderParents(false)->setMinDepth(2)->setMaxDepth(2); ?>
					</div>
				</div>
			</div>
		</div>

		<div id="breadcrumbs"></div>


		
		
		
	<?php echo $this->layout()->content ?>

	</div>

</body>
</html>
