<script>

	var selectedGroupId = 1;
	var clickedUserId = -1;
	var dataTable;

	$(function(){

		updateTree();
		showUsers();

		$("#EditGroupLink").click(function(){
			$("#modalholder").load("<?php echo $this->SE_path . '/groups/editgroup?gid=' ?>" + selectedGroupId);
		});

		$("#CreateSubGroupLink").click(function(){
			$("#modalholder").load("<?php echo $this->SE_path . '/groups/addsubgroup?gid=' ?>" + selectedGroupId);
		});
	
		$("#CreateUserLink").click(function(){
			$("#modalholder").load("<?php echo $this->SE_path . '/users/userform?state=new&gid=' ?>" + selectedGroupId);
		});

		$("#RemoveGroupLink").click(function(){
			$("#modalholder").load("<?php echo $this->SE_path . '/groups/deletegroup?gid=' ?>" + selectedGroupId);
		});

		$("#ViewUserLink").click(function(){
			$("#modalholder").load("<?php echo $this->SE_path . '/users/userform?state=show&pid=' ?>" + clickedUserId);
		});

		$("#EditUserLink").click(function(){
			$("#modalholder").load("<?php echo $this->SE_path . '/users/userform?state=edit&pid=' ?>" + clickedUserId);
		});
                
                $("#MoveUserLink").click(function(){
			$("#modalholder").load("<?php echo $this->SE_path . '/users/move?oldgid=' ?>" + selectedGroupId);
		});

		$("#RemoveUserLink").click(function(){
			alert("Not Yet Implemented");
			//$("#modalholder").load("<?php echo $this->SE_path . '/users/userform?state=edit&pid=' ?>" + clickedUserId);
		});

		$("#MultiTaskLink").click(function(){

			var selectedArr = new Array();
                        $(".selectUser:checked").each( 
                            function(k,v) { 
                                selectedArr.push($(v).attr("value"));
                            } 
                        );

                        
			$("#modalholder").load("<?php echo $this->SE_path . '/usertasks/getalltasksforuser' ?>", new makePostArray(selectedArr));
		});
                
        $("#TaskTemplatesLink").click(function(){
                    
            $("#modalholder").load("<?php echo $this->SE_path . '/tasktemplate/managetasktemplates' ?>");
			
		});	

		$("#selectAllCheckbox").click(function(){

			if($(this).attr("checked"))
			{
				$(".selectUser").attr("checked","checked");
			}else{
				$(".selectUser").removeAttr("checked");
			}
			
		});
	});


	function makePostArray(jspostArr) {
		   this.jspostArr = jspostArr;
		}
	
	function updateTree()
	{
		$("#grouptree").jstree({ 
			"ui" : {	
				"initially_select" : [ "tree"+selectedGroupId ]
			},
			"json_data" : {
				"ajax" : {
					"url" : "<?php echo $this->SE_path . '/groups/getgroup' ?>",
					"data" : function (n) { 
						return { id : n.attr ? n.attr("id") : 0 }; 
					},
					"progressive_render" : true,
					"progressive_unload" : true
				}
			},
			"plugins" : [ "themes", "json_data","ui" ]
		}).bind("select_node.jstree", function (event, data) { 
			selectedGroupId = data.rslt.obj.attr("groupid");

			groupname =  data.rslt.obj.attr("groupname");

			$("#groupname").html(groupname);

			updateUsers();
			
		});

	}

	function updateUsers()
	{
		if($("#userstable").length)
		{
			$("#userstable").dataTable().fnReloadAjax("<?php echo $this->SE_path . '/users/getusers?gid=' ?>"+selectedGroupId);
		}

		$("#bofhexcuse").html(NewExcuse());
	}


	function showUsers()
	{
		dataTable = $("#userstable").dataTable({
			"bSort":true,
			"aaSorting" : [[ 5, "desc" ]],
			 "aoColumns": [
			               { "bSortable": false },
			               null,
			               null,
			               null,
			               null,
			               null
			             ] ,
			"iDisplayLength": -1,
			//"aLengthMenu": [[-1, 10, 25, 50], ["All",10, 25, 50]],
			//"sDom": '<"row-fluid"fl><"row-fluid"<"btn-group span6"p><"span6"i>>r<"usertablewrapper"t>',
			"sDom": '<"row-fluid"f>r<"usertablewrapper"t>',
	        "bProcessing": true,
	        "oLanguage": {
	            "sProcessing": "Data ophalen...",
	            "sLengthMenu": "Aantal resultaten per pagina: _MENU_ ",
	            "sZeroRecords": "Geen resultaten gevonden",
	            "sInfo": "_START_ tot _END_ van _TOTAL_ resultaten",
	            "sInfoEmpty": "Geen resultaten om weer te geven",
	            "sInfoFiltered": " (gefilterd uit _MAX_ resultaten)",
	            "sInfoPostFix": "",
	            "sSearch": "Zoeken:",
	            "sEmptyTable": "Geen resultaten aanwezig in de tabel",
	            "sInfoThousands": ".",
	            "sLoadingRecords": "Een moment geduld aub - bezig met laden...",
	            "oPaginate": {
	                "sFirst": "Eerste",
	                "sLast": "Laatste",
	                "sNext": "Volgende",
	                "sPrevious": "Vorige"
	            }
	        }, 
	        "fnRowCallback": function( nRow, aData, iDisplayIndex ) {
	            /* Append the grade to the default row class name */
	          
	                $('td:eq(0)', nRow).html( "<input class='selectUser' type=checkbox name='user[]' value='"+ aData[0] +"'/>"  );
	            
	        }

	    });

		//table rightclick
		$('#userstable tbody').on("contextmenu",'tr', function(e) {
    		var clickedElem = $(this);
    		
    		$("#useractions > ul > li").addClass('open');

    		clickedUserId = clickedElem.find(".selectUser").attr("value");

    	
        	
    		$("#useractions").css({       
            		position: "absolute",
    		        top: e.pageY + "px",
    		        left: e.pageX + "px"});		

 	       return false;
    	});
		
		 $('html').on('click',function(){
			 $("#useractions > ul > li").removeClass('open');
		 });
		
	}

	
</script>

<div class="alert">
	<a class="close" data-dismiss="alert">×</a> <strong>Warning!</strong> <span id="bofhexcuse"></span>
</div>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span3">
			<h1>Groepen</h1>

			<div id="grouptree">
				<!-- tree will be rendered here -->
			</div>
		</div>
		<div class="span9">

			<ul class="nav nav-pills ">
				<li><h2 style="line-height: 30px">
						Groep <span id="groupname"></span>
					</h2></li>
				<li class="dropdown" id="menu1"><a class="dropdown-toggle" data-toggle="dropdown" href="#menu1"> Acties <b
						class="caret"></b>
				</a>
					<ul class="dropdown-menu">
						<li><a id="CreateUserLink" href="#"><i class="icon-user"></i> Gebruiker maken</a></li>
                                                <li><a id="MoveUserLink" href="#"><i class="icon-move"></i> Gebruikers verplaatsen</a></li>
                                                <li class="divider"></li>
						<li><a id="CreateSubGroupLink" href="#"><i class="icon-plus"></i> Subgroep maken</a></li>
						<li><a id="EditGroupLink" href="#"><i class="icon-pencil"></i> Groep bewerken</a></li>
						<li><a id="RemoveGroupLink" href="#"> <i class="icon-remove"></i> Groep verwijderen</a></li>
						<li class="divider"></li>
						<li><a id="MultiTaskLink" href="#"><i class="icon-list-alt"></i> Taken uitvoeren</a></li>
                                                <li><a id="TaskTemplatesLink" href="#"><i class="icon-list-alt"></i> Taak templates beheren</a></li>
					</ul>
				</li>
			</ul>
			<div id="groepcontent">
				<table id='userstable' class='table'>
				<thead>
				<tr>
				<td><input type="checkbox" id="selectAllCheckbox"/></td>
				<td> ID <i class='icon-chevron-down'></i><i class='icon-chevron-up'></i></td>
				<td>Voornaam <i class='icon-chevron-down'></i><i class='icon-chevron-up'></i></td>
				<td>Achternaam <i class='icon-chevron-down'></i><i class='icon-chevron-up'></i></td>
				<td>Gebruikersnaam <i class='icon-chevron-down'></i><i class='icon-chevron-up'></i></td>
				
				<td>Gemaakt op <i class='icon-chevron-down'></i><i class='icon-chevron-up'></i></td>
			</tr>
		</thead>
				</table>
			</div>
		</div>
	</div>
</div>

<div id="modalholder"></div>

<div id="useractions">
	<ul class="nav nav-pills">
		<li class="dropdown">
			<ul class="dropdown-menu">
				<li><a href="javascript:void(0)" id="ViewUserLink"><i class="icon-user"></i> Bekijken</a></li>
				<li><a href="javascript:void(0)" id="EditUserLink"><i class="icon-pencil"></i> Bewerken</a></li>
				<li><a href="javascript:void(0)" id="RemoveUserLink"> <i class="icon-remove"></i> Verwijderen
				</a></li>
			</ul>
		</li>
	</ul>
</div>
