



<div class="page-header">
	<h1>Dashboard</h1>
</div>


<div class="row-fluid">
	<div class="span12">
		<h2>Task queue</h2>


		<table class="table">
			<thead>
				<tr>
					<td>Group id</td>
					<td>Person id</td>
					<td>Task</td>

					<td>Error count</td>
					<td>Error messages</td>
				</tr>
			</thead>
			<tbody>


				<?php 
				foreach ($this->taskQueue as $tq)
				{?>

				<tr
				<?php if($tq->getErrorCount()>0){echo 'class="alert alert-error"';} ?>>
					<td><?php echo $tq->getGroupid() ?>
					</td>
					<td><?php echo $tq->getPersonid() ?>
					</td>

					<td><span class="label label-inverse" data-toggle="collapse"
						data-target="<?php echo "#tqid" . $tq->getId(); ?>"> <?php echo $tq->gettask_class() ?>
					</span> <pre id="<?php echo "tqid" . $tq->getId(); ?>"
							class="collapse out"><?php var_dump( $tq->getConfiguration()) ?></pre>
					</td>


					<td><?php echo $tq->getErrorCount() ?>
					</td>
					<td><pre><?php echo $tq->getErrorMessages() ?></pre>
					</td>
				</tr>

				<?php } ?>
			</tbody>
		</table>
	</div>


</div>

