

<div class="page-header">
<h1>Dashboard</h1>
</div>


<div class="row">
	<div class="span6">
		<h2>Group task queue</h2>


		<table class="table">
			<thead>
				<tr>
					<td>Task Naam</td>
					<td>Configuratie</td>
					<td>Group id</td>
					<td>Error count</td>
					<td>Error messages</td>
				</tr>
			</thead>
			<tbody>

				<?php foreach ($this->groupTaskQueue as $gtq)
				{
					?>

				<tr <?php if($gtq->getErrorCount()>0){echo 'class="alert alert-error"';} ?>>
					<td><?php echo $gtq->getTaskname() ?>
					</td>
					<td><pre><?php var_dump( $gtq->getConfiguration()) ?></pre>
					</td>
					<td><?php echo $gtq->getGroup_Id() ?>
					</td>
					<td><?php echo $gtq->getErrorCount() ?>
					</td>
					<td><pre><?php echo $gtq->getErrorMessages() ?></pre>
					</td>
				</tr>

				<?php
	} ?>
			</tbody>
		</table>
	</div>

	<div class="span6">
	<h2>Person task queue</h2>
	
		<table class="table">
			<thead>
				<tr>
					<td>Task Naam</td>
					<td>Configuratie</td>
					<td>Person id</td>
					<td>Error count</td>
					<td>Error messages</td>
				</tr>
			</thead>
			<tbody>

				<?php foreach ($this->personTaskQueue as $gtq)
				{
					?>

				<tr <?php if($gtq->getErrorCount()>0){echo 'class="alert alert-error"';}else{echo 'class="alert"';} ?>>
					<td><?php echo $gtq->getTaskname() ?>
					</td>
					<td><pre><?php var_dump( $gtq->getConfiguration()) ?></pre>
					</td>
					<td><?php echo $gtq->getPerson_Id() ?>
					</td>
					<td><?php echo $gtq->getErrorCount() ?>
					</td>
					<td><pre><?php echo $gtq->getErrorMessages() ?></pre>
					</td>
				</tr>

				<?php
			} ?>
			</tbody>
		</table>
	
	</div>
</div>

