
<?php

function render_tree($roots)
{
	if(count($roots) === 0)
		return;
	
	echo "<ul class='hi'>\n";
	foreach($roots as $group)
	{
		echo "<li>\n<a href='#sqdf'>";
		echo $group->getName() . "(" . $group->getId() . ")" . "</a>\n";
		
		
		render_tree($group->getChildGroups());
		echo "</li>\n";
	}
	echo "</ul>\n";
}

render_tree($this->groups);

?>



<form class="well" action="<?php echo $this->SE_path . "/users/addgrouppost" ?>" method="post" id="formAddGroup">


					<p class="ui-helper-clearfix">
						<label for="parentId">Parent id:</label> <input type="text"
							id="parentId" name="parentId" />
					
					</p>
					
					<p class="ui-helper-clearfix">
						<label for="txtName">Naam:</label> <input type="text" id="txtName"
							name="txtName" />
					</p>

				<button type="submit" class="btn">Toevoegen</button>
</form>