<?php

function render_tree($roots)
{
	if(count($roots) === 0)
		return;
	
	echo "<ul class='hi'>\n";
	foreach($roots as $group)
	{
		echo "<li groupid=" .  $group->getId() . ">\n<a href='#'>";
		echo $group->getName() . "(" . $group->getId() . ")" . "</a>\n";
		
		
		render_tree($group->getChildGroups());
		echo "</li>\n";
	}
	echo "</ul>\n";
}

?>



<script>

	$(function(){


		$.fn.dataTableExt.oStdClasses.sFilter = "span6";
		$.fn.dataTableExt.oStdClasses.sLength  = "span6";
		$.fn.dataTableExt.oStdClasses.sWrapper = "well";

		$.fn.dataTableExt.oStdClasses.sPagePrevEnabled  ="btn btn-success span1";
		$.fn.dataTableExt.oStdClasses.sPagePrevDisabled   ="btn btn-danger span1";
		$.fn.dataTableExt.oStdClasses.sPageNextEnabled   ="btn btn-success ";
		$.fn.dataTableExt.oStdClasses.sPageNextDisabled   ="btn btn-danger ";

		$("#userstable").dataTable({
			"bSort":true,
			"aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
			  "sDom": '<"row-fluid"fl><"row-fluid"<"btn-group span6"p><"span6"i>>rt',//'<"row-fluid well"fl><"row-fluid well btn-group"<"span6"p><"span6"i>>rt',
	        "bProcessing": true,
	        "oLanguage": {
	            "sProcessing": "Data ophalen...",
	            "sLengthMenu": "Aantal resultaten per pagina: _MENU_ ",
	            "sZeroRecords": "Geen resultaten gevonden",
	            "sInfo": "_START_ tot _END_ van _TOTAL_ resultaten",
	            "sInfoEmpty": "Geen resultaten om weer te geven",
	            "sInfoFiltered": " (gefilterd uit _MAX_ resultaten)",
	            "sInfoPostFix": "",
	            "sSearch": "Zoeken:",
	            "sEmptyTable": "Geen resultaten aanwezig in de tabel",
	            "sInfoThousands": ".",
	            "sLoadingRecords": "Een moment geduld aub - bezig met laden...",
	            "oPaginate": {
	                "sFirst": "Eerste",
	                "sLast": "Laatste",
	                "sNext": "Volgende",
	                "sPrevious": "Vorige"
	            }
	        },
	        "sAjaxSource": 'users/getusers'
	    } );
		
		$("#grouptree").jstree()
		
		.bind("select_node.jstree", function (event, data) { 
			groupid = data.rslt.obj.attr("groupid");

			$("#userstable").dataTable().fnReloadAjax('users/getusers?gid='+groupid);
		});

		$.fn.dataTableExt.oApi.fnReloadAjax = function ( oSettings, sNewSource, fnCallback, bStandingRedraw )
		{
		    if ( typeof sNewSource != 'undefined' && sNewSource != null )
		    {
		        oSettings.sAjaxSource = sNewSource;
		    }
		    this.oApi._fnProcessingDisplay( oSettings, true );
		    var that = this;
		    var iStart = oSettings._iDisplayStart;
		    var aData = [];
		 
		    this.oApi._fnServerParams( oSettings, aData );
		     
		    oSettings.fnServerData( oSettings.sAjaxSource, aData, function(json) {
		        /* Clear the old information from the table */
		        that.oApi._fnClearTable( oSettings );
		         
		        /* Got the data - add it to the table */
		        var aData =  (oSettings.sAjaxDataProp !== "") ?
		            that.oApi._fnGetObjectDataFn( oSettings.sAjaxDataProp )( json ) : json;
		         
		        for ( var i=0 ; i<aData.length ; i++ )
		        {
		            that.oApi._fnAddData( oSettings, aData[i] );
		        }
		         
		        oSettings.aiDisplay = oSettings.aiDisplayMaster.slice();
		        that.fnDraw();
		         
		        if ( typeof bStandingRedraw != 'undefined' && bStandingRedraw === true )
		        {
		            oSettings._iDisplayStart = iStart;
		            that.fnDraw( false );
		        }
		         
		        that.oApi._fnProcessingDisplay( oSettings, false );
		         
		        /* Callback user function - for event handlers etc */
		        if ( typeof fnCallback == 'function' && fnCallback != null )
		        {
		            fnCallback( oSettings );
		        }
		    }, oSettings );
		}
		
	});
</script>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span2">
			<h1>Groepen</h1>

			<div id="grouptree">
			<?php 		
				render_tree($this->groups);
			?>
			</div>
		</div>
		<div class="span10">
			<h1>Gebruikers</h1>

			<table id="userstable" class="table">
				<thead>
					<tr>
						<td>ID</td>
						<td>Voornaam</td>
						<td>Achternaam</td>
						<td>Gebruikersnaam</td>
						<td>Actief</td>
						<td>Gemaakt op</td>
					</tr>
				</thead>
				<tbody>
					
					
					
					

				<?php
				/*foreach ($this->users as $user)
				{
					?>
					<tr>
						<td><?php echo $user->getId(); ?></td>
						<td><?php echo $user->getFirstName(); ?></td>
						<td><?php echo $user->getName(); ?></td>
						<td><?php echo $user->getAccountUserName(); ?></td>
						<td><?php echo $user->getAccountActive(); ?></td>
						<td><?php echo $user->getMadeOn(); ?></td>
					</tr>
				<?php
	}*/
?>
</tbody>
			</table>
		</div>
	</div>
</div>


