<?php

function render_tree($roots)
{
	if(count($roots) === 0)
		return;
	
	echo "<ul class='hi'>\n";
	foreach($roots as $group)
	{
		echo "<li>\n<a href='#sqdf'>";
		echo $group->getName() . "(" . $group->getId() . ")" . "</a>\n";
		
		
		render_tree($group->getChildGroups());
		echo "</li>\n";
	}
	echo "</ul>\n";
}

?>


</div>


<script>

	$(function(){
		$("#grouptree").jstree();
	});
</script>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span2">
			<h1>Groepen</h1>

			<div id="grouptree">
			<?php 		
				render_tree($this->groups);
			?>
			</div>
		</div>
		<div class="span10">
			<h1>Gebruikers</h1>

			<table class="table">
				<thead>
					<tr>
						<td>ID</td>
						<td>Voornaam</td>
						<td>Achternaam</td>
						<td>Gebruikersnaam</td>
						<td>Actief</td>
						<td>Gemaakt op</td>
					</tr>
				</thead>
				<tbody>
					
					
					
					

				<?php
				foreach ($this->users as $user)
				{
					?>
					<tr>
						<td><?php echo $user->getId(); ?></td>
						<td><?php echo $user->getFirstName(); ?></td>
						<td><?php echo $user->getName(); ?></td>
						<td><?php echo $user->getAccountUserName(); ?></td>
						<td><?php echo $user->getAccountActive(); ?></td>
						<td><?php echo $user->getMadeOn(); ?></td>
					</tr>
				<?php
	}
?>
</tbody>
			</table>
		</div>
	</div>
</div>


