
<?php $this->headScript()->captureStart() ?>
var blaat = '<?php echo $this->SE_path . "/var/dev" ?>';
<?php $this->headScript()->captureEnd() ?>


<?php

$this->headScript()->appendFile($this->SE_path . "/js/views/users.js");

?>




<div id="adduser">

	<h1>Gebruiker toevoegen</h1>

	<form>
		<div id="tab-container" class="tab-container">
			<ul class='etabs'>
				<li class='tab'><a href="#type">Kies type</a></li>
				<li class='tab'><a href="#gegevens">Gegevens invullen</a></li>
				<li class='tab'><a href="#taken">Taken</a></li>
			</ul>
			<div class="panel-container">
				<div id="type">
					
					

				<?php
				foreach ($this->types as $type)
				{
					?>
					<p class="ui-helper-clearfix">
						<input type="checkbox" name="<?php echo $type->getId() ?>"
							id="<?php echo $type->getId() ?>" /> <label
							for="<?php echo $type->getId() ?>"><?php echo $type->getTypeName() ?>
						</label>
					</p>
					
					
					
					
					<?php
				}		
				?>


			</div>
				<div id="gegevens">

					<p class="ui-helper-clearfix">
						<label for="txtFirstName">Voornaam:</label> <input type="text"
							id="txtFirstName" name="txtFirstName" />
					
					</p>
					
					<p class="ui-helper-clearfix">
						<label for="txtName">Naam:</label> <input type="text" id="txtName"
							name="txtName" />
					</p>


				</div>
				<div id="taken">
					<h2>CSS Styles for these tabs</h2>
					<!-- content -->
				</div>
			</div>
		</div>
	</form>


</div>
