<?php

namespace solideagle\scripts;

use solideagle\data_access\PlatformGA;

use solideagle\data_access\Person;

use solideagle\plugins\ga\GamExecutor;

class InitialGappImport
{

	private static $userArr = array();

	public static function doImport()
	{
		self::doRecurse(self::getGroupMembers("dbzgebruikers"));

		var_export(self::$userArr);
	}

	private static function doRecurse($members)
	{
		var_dump($members);

		foreach($members as $member)
		{
			if($member->type == "Group")
			{
				self::doRecurse(self::getGroupMembers($member->mail));
			}else{
				self::$userArr[] = $member;
			}
		}
	}

	private static function getGroupMembers($name)
	{
		$cmd = "info group " . $name;

		$res = GamExecutor::executeGamCommandGetResult($cmd);

		var_dump($res);

		$arr = explode("\n", $res);

		$retarr = array();

		foreach($arr as $line)
		{
			$parts = explode(":",$line);
			if(count($parts)>3)
			{
				$retarr[] = new gappObj(substr($parts[1],1,-6), substr($parts[2],1,-15));
			}

		}

		return $retarr;

	}

	public static function doTheDataImport()
	{
		$commands ="info user leerlingt12@dbz.be
		info user leerlingt125@dbz.be
		info user leerlingt126@dbz.be
		info user solideagle_admin2@dbz.be
		info user alexanderj@dbz.be
		info user andriesm@dbz.be
		info user baelet@dbz.be
		info user baetena@dbz.be
		info user bardynw@dbz.be
		info user bataillea@dbz.be
		info user bernaertss@dbz.be
		info user biesbrouckp@dbz.be
		info user blanckaertc@dbz.be
		info user blanckef@dbz.be
		info user blommep@dbz.be
		info user bodsonb@dbz.be
		info user bogaertn@dbz.be
		info user bonoj@dbz.be
		info user boonen@dbz.be
		info user borremansg@dbz.be
		info user bottek@dbz.be
		info user bottermans@dbz.be
		info user bourgoigniem@dbz.be
		info user boxtaelei@dbz.be
		info user braemp@dbz.be
		info user browaeysk@dbz.be
		info user callaertt@dbz.be
		info user casteleina@dbz.be
		info user cattrysses@dbz.be
		info user cauwelsl@dbz.be
		info user clauwaertt@dbz.be
		info user clinquantg@dbz.be
		info user cobbautc@dbz.be
		info user cocquyta@dbz.be
		info user collee@dbz.be
		info user coppensn@dbz.be
		info user corveleyne@dbz.be
		info user courtensa@dbz.be
		info user cuypersl@dbz.be
		info user cuytk@dbz.be
		info user debaetsi@dbz.be
		info user decoenel@dbz.be
		info user decraenes@dbz.be
		info user decramerl@dbz.be
		info user decuyperm@dbz.be
		info user dedonckere@dbz.be
		info user degeyterl@dbz.be
		info user degeyters@dbz.be
		info user degrootem@dbz.be
		info user degrootes@dbz.be
		info user dejaegere@dbz.be
		info user dekerpely@dbz.be
		info user delftr@dbz.be
		info user delmellel@dbz.be
		info user demaerteleirh@dbz.be
		info user demedtsj@dbz.be
		info user demeestera@dbz.be
		info user demoorm@dbz.be
		info user depaepejra@dbz.be
		info user depaepesra@dbz.be
		info user depetterg@dbz.be
		info user deptv@dbz.be
		info user derudderp@dbz.be
		info user desmetd@dbz.be
		info user despiegelaerem@dbz.be
		info user detemmermana@dbz.be
		info user devolxlopezm@dbz.be
		info user devriendts@dbz.be
		info user devriesem@dbz.be
		info user devuystr@dbz.be
		info user dewildeg@dbz.be
		info user dewildem@dbz.be
		info user dewitm@dbz.be
		info user dhaeseleerm@dbz.be
		info user dhondtf@dbz.be
		info user dhondtk@dbz.be
		info user dhondtke@dbz.be
		info user diericke@dbz.be
		info user dissenbergenm@dbz.be
		info user dodemonta@dbz.be
		info user duchie@dbz.be
		info user duhamels@dbz.be
		info user eeckhoutc@dbz.be
		info user eggermontj@dbz.be
		info user eussenm@dbz.be
		info user flouwa@dbz.be
		info user garred@dbz.be
		info user gheysent@dbz.be
		info user ghyselinckk@dbz.be
		info user ginnebergee@dbz.be
		info user godaertv@dbz.be
		info user goossene@dbz.be
		info user gunsj@dbz.be
		info user hemelsoetj@dbz.be
		info user heuleum@dbz.be
		info user hilgerta@dbz.be
		info user hoebekek@dbz.be
		info user holvoetp@dbz.be
		info user hosteg@dbz.be
		info user jacobsl@dbz.be
		info user jannesl@dbz.be
		info user jelassis@dbz.be
		info user keppensd@dbz.be
		info user keppensm@dbz.be
		info user leysf@dbz.be
		info user liagrem@dbz.be
		info user lippensj@dbz.be
		info user mangeleers@dbz.be
		info user marrecaup@dbz.be
		info user martinlavis@dbz.be
		info user martinp@dbz.be
		info user mathysd@dbz.be
		info user meyersa@dbz.be
		info user mispelonh@dbz.be
		info user moensc@dbz.be
		info user moermant@dbz.be
		info user nachtergaeles@dbz.be
		info user nackaertsp@dbz.be
		info user neckebroeckl@dbz.be
		info user ossieuri@dbz.be
		info user ostyns@dbz.be
		info user perneelc@dbz.be
		info user petersp@dbz.be
		info user pietersf@dbz.be
		info user piqueurl@dbz.be
		info user plaetinckv@dbz.be
		info user poppej@dbz.be
		info user pottiem@dbz.be
		info user provosth_old@dbz.be
		info user putmanr@dbz.be
		info user raemdonckl@dbz.be
		info user reunesw@dbz.be
		info user ronsses@dbz.be
		info user rooseb@dbz.be
		info user roosel@dbz.be
		info user ryckaertc@dbz.be
		info user schaubroeckh@dbz.be
		info user scheirsens@dbz.be
		info user schelstraetej@dbz.be
		info user schepensj@dbz.be
		info user schepensl@dbz.be
		info user schepensp@dbz.be
		info user schreiberm@dbz.be
		info user seldeslachtse@dbz.be
		info user simoeng@dbz.be
		info user sleeuwaertm@dbz.be
		info user spitaelsl@dbz.be
		info user staelsf@dbz.be
		info user stockmanp@dbz.be
		info user suetensl@dbz.be
		info user tackj@dbz.be
		info user tackm@dbz.be
		info user taelmann@dbz.be
		info user taveirnet@dbz.be
		info user tembuyserm@dbz.be
		info user testg@dbz.be
		info user testnaamt@dbz.be
		info user timmermansc@dbz.be
		info user tinelh@dbz.be
		info user uytterlinder@dbz.be
		info user vagenendee@dbz.be
		info user vanbossuytb@dbz.be
		info user vancraeyveltk@dbz.be
		info user vandaelet@dbz.be
		info user vandenbosschea@dbz.be
		info user vandenbusscheg@dbz.be
		info user vandendaelek@dbz.be
		info user vandendoorena@dbz.be
		info user vanderbekenl@dbz.be
		info user vanderhasseltc@dbz.be
		info user vanderschuerena@dbz.be
		info user vandewallep@dbz.be
		info user vaneetveldef@dbz.be
		info user vanherpeg@dbz.be
		info user vanheuleh@dbz.be
		info user vanhoeh@dbz.be
		info user vanhoordel@dbz.be
		info user vanlokerene@dbz.be
		info user vanmarsnillel@dbz.be
		info user vanrietk@dbz.be
		info user vanrysselberghed@dbz.be
		info user vanschelstraeteb@dbz.be
		info user vantieghemg@dbz.be
		info user vanvoorens@dbz.be
		info user vanvoorenv@dbz.be
		info user vensm@dbz.be
		info user vercauterenk@dbz.be
		info user vercauterens@dbz.be
		info user vermeulens@dbz.be
		info user vertriestp@dbz.be
		info user vervaecke@dbz.be
		info user volckaertm@dbz.be
		info user volckaerts@dbz.be
		info user volkaertd@dbz.be
		info user vynckef@dbz.be
		info user waegemanss@dbz.be
		info user wildrop@dbz.be
		info user woutersh@dbz.be
		info user wylink@dbz.be
		info user wynst@dbz.be
		info user bottem11@dbz.be
		info user casteelsv11@dbz.be
		info user clevism11@dbz.be
		info user crommelinckj11@dbz.be
		info user declercqn11@dbz.be
		info user declercqw11@dbz.be
		info user demaerteleiret11@dbz.be
		info user depoorteree11@dbz.be
		info user detemmermane11@dbz.be
		info user hofmant11@dbz.be
		info user kunnenh11@dbz.be
		info user landuytt11@dbz.be
		info user lootensn11@dbz.be
		info user segersa11@dbz.be
		info user thomasp11@dbz.be
		info user vandekerkhovea11@dbz.be
		info user vandenberghew11@dbz.be
		info user vanrentergheml11@dbz.be
		info user vanvoorend11@dbz.be
		info user winkelj11@dbz.be
		info user balliue11@dbz.be
		info user bastiaenj11@dbz.be
		info user claeysj11@dbz.be
		info user dedeurwaerdert11@dbz.be
		info user devism11@dbz.be
		info user dewildel11@dbz.be
		info user eeckhoutw11@dbz.be
		info user francoiss11@dbz.be
		info user lievensk11@dbz.be
		info user maesj11@dbz.be
		info user moonsl11@dbz.be
		info user peirsmanj11@dbz.be
		info user peterst11@dbz.be
		info user tackl11@dbz.be
		info user tinelr11@dbz.be
		info user vanbastelaeree11@dbz.be
		info user vanhuylenbroeckt11@dbz.be
		info user vilyna11@dbz.be
		info user wautersd11@dbz.be
		info user bovyna11@dbz.be
		info user cuyversl11@dbz.be
		info user decokeret11@dbz.be
		info user decouvreurr11@dbz.be
		info user decuyperl11@dbz.be
		info user decuypers11@dbz.be
		info user delcourtn11@dbz.be
		info user devisscherm11@dbz.be
		info user dewulfb11@dbz.be
		info user geenensl11@dbz.be
		info user goessensl11@dbz.be
		info user lasseelj11@dbz.be
		info user neytm11@dbz.be
		info user ortegatl11@dbz.be
		info user petitf11@dbz.be
		info user vanautrevey11@dbz.be
		info user vandeneyndel11@dbz.be
		info user vandeputtea11@dbz.be
		info user veermeerl11@dbz.be
		info user vervennej11@dbz.be
		info user alenusj11@dbz.be
		info user artoiso11@dbz.be
		info user bertl11@dbz.be
		info user boonenl11@dbz.be
		info user cnuddem11@dbz.be
		info user coigniezm11@dbz.be
		info user deblanderv11@dbz.be
		info user defrancqh11@dbz.be
		info user deruyckc11@dbz.be
		info user heyndrickxf11@dbz.be
		info user moensm11@dbz.be
		info user moreelsh11@dbz.be
		info user olivierl11@dbz.be
		info user ranganl11@dbz.be
		info user rasschaertb11@dbz.be
		info user schepensa11@dbz.be
		info user schepensc11@dbz.be
		info user schobbent11@dbz.be
		info user steyaerte11@dbz.be
		info user tkindtv11@dbz.be
		info user vandammei11@dbz.be
		info user vandurmen11@dbz.be
		info user vanhaerena11@dbz.be
		info user vannieuwenhuysee11@dbz.be
		info user vermeirenm11@dbz.be
		info user adamss11@dbz.be
		info user bogaertj11@dbz.be
		info user brouilletc11@dbz.be
		info user burssensa11@dbz.be
		info user calmeynm11@dbz.be
		info user colmantj11@dbz.be
		info user criela11@dbz.be
		info user crommelincks11@dbz.be
		info user denevej11@dbz.be
		info user deryckm11@dbz.be
		info user deweirdti11@dbz.be
		info user eeckhoutj11@dbz.be
		info user goossensc11@dbz.be
		info user goossensl11@dbz.be
		info user jacobsm11@dbz.be
		info user kollarackall11@dbz.be
		info user raess11@dbz.be
		info user ryckaerta11@dbz.be
		info user vandekerckhovee11@dbz.be
		info user vanderleenem11@dbz.be
		info user vermeiref11@dbz.be
		info user verschatsem11@dbz.be
		info user verstappeb11@dbz.be
		info user aeltermanj11@dbz.be
		info user callenst11@dbz.be
		info user cooremanr11@dbz.be
		info user deblanderf11@dbz.be
		info user decoenea11@dbz.be
		info user desmeta11@dbz.be
		info user devosk11@dbz.be
		info user dhondtm11@dbz.be
		info user dhosschea11@dbz.be
		info user haesebeyth11@dbz.be
		info user hernalsteenw11@dbz.be
		info user kindtb11@dbz.be
		info user magniettem11@dbz.be
		info user mettles11@dbz.be
		info user thielemansy11@dbz.be
		info user vandammej11@dbz.be
		info user vanrysseghemb11@dbz.be
		info user vercammenc11@dbz.be
		info user verkerckeb11@dbz.be
		info user verliefdej111@dbz.be
		info user verliefdej112@dbz.be
		info user verstraetenl11@dbz.be
		info user walleynr11@dbz.be
		info user decampenaeret11@dbz.be
		info user deconincka11@dbz.be
		info user decoussemakera11@dbz.be
		info user demulderd11@dbz.be
		info user depoorterf11@dbz.be
		info user desmetn11@dbz.be
		info user devriendtd11@dbz.be
		info user dewittel11@dbz.be
		info user dhaenensl11@dbz.be
		info user dhondtn11@dbz.be
		info user folensb11@dbz.be
		info user heyerickv11@dbz.be
		info user heynderickxb11@dbz.be
		info user icteerstes10@dbz.be
		info user poulint11@dbz.be
		info user raevensl11@dbz.be
		info user slabbinckf11@dbz.be
		info user terhorstt11@dbz.be
		info user tytgatm11@dbz.be
		info user vandammer111@dbz.be
		info user vaneenleerlio11@dbz.be
		info user vanrooser11@dbz.be
		info user vanweldenf11@dbz.be
		info user veldemang11@dbz.be
		info user verscheldenj11@dbz.be
		info user vuyef11@dbz.be
		info user albrechti11@dbz.be
		info user boudrezj11@dbz.be
		info user braeckmanm11@dbz.be
		info user bruggeh11@dbz.be
		info user buyssec11@dbz.be
		info user callebautm11@dbz.be
		info user caselladendoovent11@dbz.be
		info user debeuckelaeres11@dbz.be
		info user dehainautl11@dbz.be
		info user demeyl11@dbz.be
		info user depauwe11@dbz.be
		info user dermautw11@dbz.be
		info user devleeschauwerj11@dbz.be
		info user dhulstert11@dbz.be
		info user eeckhoutm11@dbz.be
		info user janssense12@dbz.be
		info user meulemane11@dbz.be
		info user peetersr12@dbz.be
		info user rombautm11@dbz.be
		info user sapj11@dbz.be
		info user vandammer112@dbz.be
		info user vanholmj11@dbz.be
		info user vanlangenhovec11@dbz.be
		info user vanwijnsberghec11@dbz.be
		info user verlindeng11@dbz.be
		info user verschurenw12@dbz.be
		info user willemsi11@dbz.be
		info user wuytsl11@dbz.be
		info user artn11@dbz.be
		info user boeym11@dbz.be
		info user decockl11@dbz.be
		info user dejaegerea11@dbz.be
		info user demaertelaerel11@dbz.be
		info user demuynckl11@dbz.be
		info user deschamphelaerem11@dbz.be
		info user deweertb11@dbz.be
		info user garreb11@dbz.be
		info user hennesc11@dbz.be
		info user heynemane11@dbz.be
		info user lenaertss11@dbz.be
		info user liegeoise11@dbz.be
		info user maese11@dbz.be
		info user naessense11@dbz.be
		info user nauwynckw11@dbz.be
		info user nolletj11@dbz.be
		info user osaerh11@dbz.be
		info user piller11@dbz.be
		info user roggen11@dbz.be
		info user vandenbosschec11@dbz.be
		info user vanheckef11@dbz.be
		info user vankerkhovena11@dbz.be
		info user vanrespaillee11@dbz.be
		info user vanveirdeghemn11@dbz.be
		info user allegaertm11@dbz.be
		info user bautsj11@dbz.be
		info user bauwensl11@dbz.be
		info user daoudil11@dbz.be
		info user dekeysers11@dbz.be
		info user deloosel11@dbz.be
		info user derammelaerem11@dbz.be
		info user desseync11@dbz.be
		info user dhaesej11@dbz.be
		info user elhmoudo11@dbz.be
		info user elleboudtm11@dbz.be
		info user evraerty11@dbz.be
		info user goossensk11@dbz.be
		info user janssensj11@dbz.be
		info user pauwelsa11@dbz.be
		info user petersh11@dbz.be
		info user rousseauxl11@dbz.be
		info user tacks11@dbz.be
		info user vanderlindena11@dbz.be
		info user vanoverscheldee11@dbz.be
		info user vanparysw11@dbz.be
		info user verstuyfts11@dbz.be
		info user willemsl11@dbz.be
		info user baekes11@dbz.be
		info user brantst11@dbz.be
		info user broddelezb11@dbz.be
		info user cnuddek11@dbz.be
		info user collem11@dbz.be
		info user depelsemaekere11@dbz.be
		info user desmete112@dbz.be
		info user gaoj11@dbz.be
		info user geeraertm11@dbz.be
		info user gernayj11@dbz.be
		info user huughee11@dbz.be
		info user kloeckr11@dbz.be
		info user mareenl11@dbz.be
		info user remmerya11@dbz.be
		info user slockt11@dbz.be
		info user smett11@dbz.be
		info user tranchetj11@dbz.be
		info user vanhoenackere11@dbz.be
		info user vanlangenhoveb11@dbz.be
		info user verbruggena11@dbz.be
		info user verhoeyenl11@dbz.be
		info user vermaerkeh11@dbz.be
		info user verstraetel11@dbz.be
		info user waelesa11@dbz.be
		info user wiemem11@dbz.be
		info user audenaertt11@dbz.be
		info user backelandtc11@dbz.be
		info user baerts11@dbz.be
		info user bruynogher11@dbz.be
		info user callewaertn11@dbz.be
		info user clerensl11@dbz.be
		info user cooremane11@dbz.be
		info user debyserm11@dbz.be
		info user dermautp11@dbz.be
		info user deryckea11@dbz.be
		info user desmetq11@dbz.be
		info user devenynw11@dbz.be
		info user devosv11@dbz.be
		info user hanssensy11@dbz.be
		info user hensk11@dbz.be
		info user hertveldtf11@dbz.be
		info user maenhaute11@dbz.be
		info user pennincke11@dbz.be
		info user remyl11@dbz.be
		info user rottierss11@dbz.be
		info user vancauwenberghea11@dbz.be
		info user vandenabeelen11@dbz.be
		info user vandenheedel11@dbz.be
		info user vanhoordel11@dbz.be
		info user vincep11@dbz.be
		info user decraenel11@dbz.be
		info user delangheh11@dbz.be
		info user deroref11@dbz.be
		info user devriezed11@dbz.be
		info user dewildemana11@dbz.be
		info user dhaeyerp11@dbz.be
		info user duchauc11@dbz.be
		info user eechautea11@dbz.be
		info user eeckhoutc11@dbz.be
		info user gerardih11@dbz.be
		info user hendrickxb11@dbz.be
		info user moensa11@dbz.be
		info user roost11@dbz.be
		info user theunissenj11@dbz.be
		info user vangeytem11@dbz.be
		info user vanlaeree11@dbz.be
		info user vanmaelej11@dbz.be
		info user vanmullemm11@dbz.be
		info user vanneremn11@dbz.be
		info user vanparijse11@dbz.be
		info user verhaeghel11@dbz.be
		info user vermeerschr11@dbz.be
		info user verschurenl11@dbz.be
		info user waesa11@dbz.be
		info user wattynl11@dbz.be
		info user buseynei11@dbz.be
		info user debaetsr11@dbz.be
		info user debiet11@dbz.be
		info user deherdti11@dbz.be
		info user demeyera11@dbz.be
		info user deridderw11@dbz.be
		info user deroevep11@dbz.be
		info user desoetef11@dbz.be
		info user eylenboscha11@dbz.be
		info user goemaerec11@dbz.be
		info user lootenst11@dbz.be
		info user meersschautm11@dbz.be
		info user moreelst11@dbz.be
		info user mullere11@dbz.be
		info user nysj11@dbz.be
		info user rombauta11@dbz.be
		info user stalpaertv11@dbz.be
		info user vanavermaetf11@dbz.be
		info user vanbeverenl11@dbz.be
		info user vandermeerscht11@dbz.be
		info user vanderpoortenl11@dbz.be
		info user vanrenterghema11@dbz.be
		info user vanwambekel11@dbz.be
		info user calish11@dbz.be
		info user callaerta11@dbz.be
		info user deriddert11@dbz.be
		info user deveirmanb11@dbz.be
		info user devosj11@dbz.be
		info user grothh11@dbz.be
		info user haentjensk11@dbz.be
		info user huygef11@dbz.be
		info user lefevrej11@dbz.be
		info user leurquaine11@dbz.be
		info user martenst11@dbz.be
		info user tyberghiend11@dbz.be
		info user uyttendaeleg11@dbz.be
		info user vanasschem11@dbz.be
		info user vandendriesf11@dbz.be
		info user vanderelstv11@dbz.be
		info user vanderstedey11@dbz.be
		info user vanelsackerg11@dbz.be
		info user vanquaethemf11@dbz.be
		info user vervaekev11@dbz.be
		info user bonnet10@dbz.be
		info user debruynk10@dbz.be
		info user deschuymert10@dbz.be
		info user deweertl10@dbz.be
		info user dhaenensc10@dbz.be
		info user feysm10@dbz.be
		info user helderweirtj10@dbz.be
		info user ipersr10@dbz.be
		info user leerling1t10@dbz.be
		info user leerling2t10@dbz.be
		info user lievensm10@dbz.be
		info user maest10@dbz.be
		info user moensm10@dbz.be
		info user sebrechtsm10@dbz.be
		info user segersr10@dbz.be
		info user vandammef10@dbz.be
		info user vandenbosschj10@dbz.be
		info user vrielinckr10@dbz.be
		info user vuygem10@dbz.be
		info user walravensj10@dbz.be
		info user debosscherj10@dbz.be
		info user decockerj10@dbz.be
		info user deconinckj10@dbz.be
		info user deridderp10@dbz.be
		info user dewitteb10@dbz.be
		info user dewittem10@dbz.be
		info user kollarackalk10@dbz.be
		info user kygneem10@dbz.be
		info user lippensj10@dbz.be
		info user palmersr10@dbz.be
		info user raesj10@dbz.be
		info user rimbauts10@dbz.be
		info user ronsser10@dbz.be
		info user sprangersf10@dbz.be
		info user vankwikelberx10@dbz.be
		info user vanrenterghem10@dbz.be
		info user vekemanl10@dbz.be
		info user volckaertl10@dbz.be
		info user vyvermanj10@dbz.be
		info user wolfcariust10@dbz.be
		info user adamsm10@dbz.be
		info user castroroegiet10@dbz.be
		info user hellebuyckm10@dbz.be
		info user hinnekensm10@dbz.be
		info user laertem10@dbz.be
		info user lippenss10@dbz.be
		info user pauwelync10@dbz.be
		info user roegiersa10@dbz.be
		info user roelandtsf10@dbz.be
		info user schaubroeckj10@dbz.be
		info user vandenhautteh10@dbz.be
		info user vandeputtew10@dbz.be
		info user vanderschuers10@dbz.be
		info user vandewoestynel11@dbz.be
		info user vangeeteruyew10@dbz.be
		info user vanovostj10@dbz.be
		info user verbruggeni10@dbz.be
		info user verdonckl10@dbz.be
		info user verhaestf10@dbz.be
		info user vindevogelm10@dbz.be
		info user allietm10@dbz.be
		info user belpairel10@dbz.be
		info user buysem10@dbz.be
		info user debackers10@dbz.be
		info user dekerpell10@dbz.be
		info user delensv10@dbz.be
		info user denevej10@dbz.be
		info user desmetg10@dbz.be
		info user gheeraerta10@dbz.be
		info user ingelaerer10@dbz.be
		info user lagaj10@dbz.be
		info user lamotef10@dbz.be
		info user matthijsv10@dbz.be
		info user matthysh10@dbz.be
		info user meirlaend10@dbz.be
		info user mertensl10@dbz.be
		info user mikkelsenl10@dbz.be
		info user onghenaa10@dbz.be
		info user paelincke10@dbz.be
		info user pelfrenej10@dbz.be
		info user saeyst10@dbz.be
		info user steyaertm10@dbz.be
		info user vandeveldea10@dbz.be
		info user vanoverschelm10@dbz.be
		info user bloemc10@dbz.be
		info user brionn10@dbz.be
		info user clementa10@dbz.be
		info user dbzvom10@dbz.be
		info user dekuyperm10@dbz.be
		info user delembret10@dbz.be
		info user destrooperh10@dbz.be
		info user develterj10@dbz.be
		info user heysef10@dbz.be
		info user holvoete10@dbz.be
		info user hostea10@dbz.be
		info user jacobsm10@dbz.be
		info user jannisr10@dbz.be
		info user labijnm10@dbz.be
		info user lauwaertsa10@dbz.be
		info user meeremanst10@dbz.be
		info user provostf10@dbz.be
		info user rogiersj10@dbz.be
		info user vanderstraetp10@dbz.be
		info user vermoter10@dbz.be
		info user verseler10@dbz.be
		info user vonckm10@dbz.be
		info user boonev10@dbz.be
		info user degraevet10@dbz.be
		info user derorep10@dbz.be
		info user deruyterb10@dbz.be
		info user desmedtm10@dbz.be
		info user desmetm10@dbz.be
		info user geeraertj10@dbz.be
		info user goyvaertsm10@dbz.be
		info user haegemanh10@dbz.be
		info user hensw10@dbz.be
		info user maenhautl10@dbz.be
		info user mortierl10@dbz.be
		info user oryew10@dbz.be
		info user sabbea10@dbz.be
		info user sapynf10@dbz.be
		info user theunissenl10@dbz.be
		info user theyst10@dbz.be
		info user vandoorselaed10@dbz.be
		info user vaneldika10@dbz.be
		info user vanhoveg10@dbz.be
		info user vanpoeckw10@dbz.be
		info user verschueres10@dbz.be
		info user verstraetea10@dbz.be
		info user vynckea10@dbz.be
		info user bess10@dbz.be
		info user cosijnj10@dbz.be
		info user dekeukelaerer10@dbz.be
		info user demeyera10@dbz.be
		info user derijckes10@dbz.be
		info user desmetb10@dbz.be
		info user elakarir11@dbz.be
		info user gallete10@dbz.be
		info user geamanua10@dbz.be
		info user gevaertm10@dbz.be
		info user gielenl10@dbz.be
		info user goeminnej10@dbz.be
		info user leroyj10@dbz.be
		info user mertensc10@dbz.be
		info user mortiert101@dbz.be
		info user parmentierj10@dbz.be
		info user steenackersg10@dbz.be
		info user teirlynckl10@dbz.be
		info user vereekenr10@dbz.be
		info user weymaerea10@dbz.be
		info user willemsb10@dbz.be
		info user windeye10@dbz.be
		info user andriesv10@dbz.be
		info user billiauwk09@dbz.be
		info user boffeb10@dbz.be
		info user debaeres10@dbz.be
		info user depottera10@dbz.be
		info user derooe10@dbz.be
		info user devliegherj10@dbz.be
		info user dhondtb10@dbz.be
		info user gezelsj10@dbz.be
		info user goedertierr10@dbz.be
		info user haerensm10@dbz.be
		info user hanssensm10@dbz.be
		info user laevenss10@dbz.be
		info user lagaste10@dbz.be
		info user liue10@dbz.be
		info user mestdagh10@dbz.be
		info user michielsg10@dbz.be
		info user vandaeleh10@dbz.be
		info user vandersmisseh10@dbz.be
		info user verliefdena10@dbz.be
		info user vermieschf10@dbz.be
		info user willemsr10@dbz.be
		info user baeler10@dbz.be
		info user bekaertr10@dbz.be
		info user cabadaisy10@dbz.be
		info user debraekeleerm10@dbz.be
		info user decockj10@dbz.be
		info user denevel10@dbz.be
		info user desmetb101@dbz.be
		info user dewittea10@dbz.be
		info user dhoorea10@dbz.be
		info user missinnei10@dbz.be
		info user notterdaemej10@dbz.be
		info user pattyne10@dbz.be
		info user pycka10@dbz.be
		info user ruysschaertm11@dbz.be
		info user thienpontv10@dbz.be
		info user thieriea10@dbz.be
		info user vanbaeveghema10@dbz.be
		info user vandenabbeele10@dbz.be
		info user vanhonackerj10@dbz.be
		info user verkerkenl10@dbz.be
		info user vermeirenn10@dbz.be
		info user bosschemi10@dbz.be
		info user cannied10@dbz.be
		info user christiaensm10@dbz.be
		info user coenel10@dbz.be
		info user cornill10@dbz.be
		info user decannieret10@dbz.be
		info user decockera10@dbz.be
		info user deprezm10@dbz.be
		info user desimpelaerel10@dbz.be
		info user deveirmant10@dbz.be
		info user dotselaeree10@dbz.be
		info user everaertl11@dbz.be
		info user lullya10@dbz.be
		info user spaasg10@dbz.be
		info user vandenheedem10@dbz.be
		info user vandevijverm10@dbz.be
		info user vanheckc10@dbz.be
		info user vansteenbergm10@dbz.be
		info user vermassenj10@dbz.be
		info user vincentl10@dbz.be
		info user wiemej10@dbz.be
		info user caudalm10@dbz.be
		info user deboosc10@dbz.be
		info user delbaereb10@dbz.be
		info user derycko10@dbz.be
		info user desmetc10@dbz.be
		info user desutterj10@dbz.be
		info user dewildel10@dbz.be
		info user dhontc10@dbz.be
		info user houthuyss10@dbz.be
		info user lauwaertc10@dbz.be
		info user lauwaertst10@dbz.be
		info user matthijsd10@dbz.be
		info user moorst10@dbz.be
		info user mortiert10@dbz.be
		info user schalckn10@dbz.be
		info user sergeanti10@dbz.be
		info user vandepittes10@dbz.be
		info user vanongevallet10@dbz.be
		info user wattyng10@dbz.be
		info user westa10@dbz.be
		info user artoisg10@dbz.be
		info user debaetsk10@dbz.be
		info user debruynem10@dbz.be
		info user decortef11@dbz.be
		info user degrooteg10@dbz.be
		info user delbooe10@dbz.be
		info user ducheynea10@dbz.be
		info user haedensf10@dbz.be
		info user lievensj10@dbz.be
		info user maesl10@dbz.be
		info user mertensm12@dbz.be
		info user michielss10@dbz.be
		info user reunest10@dbz.be
		info user robertim10@dbz.be
		info user schelstraeter10@dbz.be
		info user steyaertl10@dbz.be
		info user vanackerp10@dbz.be
		info user vandenhendes10@dbz.be
		info user vandermeerenf10@dbz.be
		info user vandesompelet10@dbz.be
		info user vanhoorebeket10@dbz.be
		info user vanmarckeh10@dbz.be
		info user vannieuwenhum10@dbz.be
		info user verbauwenf10@dbz.be
		info user weyersm10@dbz.be
		info user bonroyw10@dbz.be
		info user brysbaertm10@dbz.be
		info user bulensj10@dbz.be
		info user decraenes10@dbz.be
		info user dekeukelaerek10@dbz.be
		info user demerliera10@dbz.be
		info user depauws10@dbz.be
		info user devriesem10@dbz.be
		info user dujardinl10@dbz.be
		info user ediersn10@dbz.be
		info user grusling10@dbz.be
		info user jacobsd10@dbz.be
		info user jacobse10@dbz.be
		info user merchiersh10@dbz.be
		info user nimmegeersb10@dbz.be
		info user oosterlinckr10@dbz.be
		info user vandammel10@dbz.be
		info user vanhoveb10@dbz.be
		info user vantroysv10@dbz.be
		info user vennemans10@dbz.be
		info user verweem10@dbz.be
		info user wulbrechts10@dbz.be
		info user zabekj10@dbz.be
		info user bogaertl10@dbz.be
		info user carremansj10@dbz.be
		info user debruynel10@dbz.be
		info user declercqm10@dbz.be
		info user degraevej10@dbz.be
		info user devroea10@dbz.be
		info user devylderj10@dbz.be
		info user dhaesen10@dbz.be
		info user gasthuysn10@dbz.be
		info user ghyselinckj10@dbz.be
		info user goditiaboisl10@dbz.be
		info user goossensq10@dbz.be
		info user hoefmank10@dbz.be
		info user lambertn10@dbz.be
		info user lefeverey10@dbz.be
		info user meersschaertw10@dbz.be
		info user noyenh10@dbz.be
		info user plasschaerta10@dbz.be
		info user stevensp10@dbz.be
		info user temmermanf10@dbz.be
		info user vanbendegema10@dbz.be
		info user vandenherrewh10@dbz.be
		info user vanderheydenj10@dbz.be
		info user verbekenm10@dbz.be
		info user cartone09@dbz.be
		info user coignieza09@dbz.be
		info user debeuckelaeree09@dbz.be
		info user debosscherj09@dbz.be
		info user demeyerz09@dbz.be
		info user demulderf09@dbz.be
		info user denevet09@dbz.be
		info user desmetl09@dbz.be
		info user devost09@dbz.be
		info user dewildej09@dbz.be
		info user dosscher09@dbz.be
		info user ghiottoa09@dbz.be
		info user lesagea091@dbz.be
		info user mareenj09@dbz.be
		info user naessenss09@dbz.be
		info user rosians09@dbz.be
		info user siaul09@dbz.be
		info user testll103@dbz.be
		info user tournetm09@dbz.be
		info user vandenabbeelef09@dbz.be
		info user vandeveldee09@dbz.be
		info user vanheesvelded09@dbz.be
		info user vermieschw09@dbz.be
		info user brouilletm09@dbz.be
		info user dal-pretem09@dbz.be
		info user debaeneh09@dbz.be
		info user declerckj08@dbz.be
		info user declercqd09@dbz.be
		info user deconinckh09@dbz.be
		info user depalmenaera09@dbz.be
		info user desmetj09@dbz.be
		info user everaerta09@dbz.be
		info user fermontt09@dbz.be
		info user grype09@dbz.be
		info user hellebautl11@dbz.be
		info user lelubreg09@dbz.be
		info user lutsm09@dbz.be
		info user lybeera09@dbz.be
		info user segersj09@dbz.be
		info user serresc10@dbz.be
		info user stordiaup09@dbz.be
		info user stremusp09@dbz.be
		info user vandenbogaerdey09@dbz.be
		info user vandewoestynef09@dbz.be
		info user baelt09@dbz.be
		info user balducke09@dbz.be
		info user coutuerv09@dbz.be
		info user criela09@dbz.be
		info user cuypersc09@dbz.be
		info user deriddera09@dbz.be
		info user deruyckd09@dbz.be
		info user lammensm10@dbz.be
		info user muylaertj09@dbz.be
		info user poulins09@dbz.be
		info user roorycke09@dbz.be
		info user sleursb09@dbz.be
		info user vanneremt09@dbz.be
		info user vanrenterghemr09@dbz.be
		info user vermaerkel09@dbz.be
		info user verspeetena09@dbz.be
		info user vervynckt09@dbz.be
		info user degrevem09@dbz.be
		info user dejaegerep09@dbz.be
		info user dheedenej09@dbz.be
		info user huylebroecka09@dbz.be
		info user lisona09@dbz.be
		info user persanl09@dbz.be
		info user vannestem09@dbz.be
		info user verkerckej09@dbz.be
		info user bracquinem09@dbz.be
		info user bruggem09@dbz.be
		info user callensj09@dbz.be
		info user decaveli09@dbz.be
		info user degraevem09@dbz.be
		info user delruej09@dbz.be
		info user desmete09@dbz.be
		info user desmetw09@dbz.be
		info user dewulfc09@dbz.be
		info user janssenss09@dbz.be
		info user matthysj09@dbz.be
		info user poletf09@dbz.be
		info user robbee09@dbz.be
		info user tjampenst09@dbz.be
		info user vandenabeelee09@dbz.be
		info user vanpolt09@dbz.be
		info user audoors09@dbz.be
		info user baelh09@dbz.be
		info user boretm09@dbz.be
		info user debosscherb09@dbz.be
		info user decocks09@dbz.be
		info user degrooted09@dbz.be
		info user deloosel09@dbz.be
		info user demeyd09@dbz.be
		info user dobbelaerem09@dbz.be
		info user germonpref09@dbz.be
		info user patyna09@dbz.be
		info user remmeriel09@dbz.be
		info user schelpeq09@dbz.be
		info user vanlangenhoves09@dbz.be
		info user vanparijsc09@dbz.be
		info user veldemanm11@dbz.be
		info user vermaerkel091@dbz.be
		info user waelesr09@dbz.be
		info user audenaertb09@dbz.be
		info user dewildew09@dbz.be
		info user eeckhoutj09@dbz.be
		info user garreh09@dbz.be
		info user goemaerej09@dbz.be
		info user goemem09@dbz.be
		info user hillewaerej09@dbz.be
		info user lambrechta09@dbz.be
		info user lamotee09@dbz.be
		info user leurquaina09@dbz.be
		info user liegeoisl09@dbz.be
		info user moentjensl09@dbz.be
		info user petersr09@dbz.be
		info user stubbej09@dbz.be
		info user stuyckw09@dbz.be
		info user vanbeverene09@dbz.be
		info user vandammee09@dbz.be
		info user vandenberghel09@dbz.be
		info user vandesteenef09@dbz.be
		info user vandewielev09@dbz.be
		info user vanheuleh09@dbz.be
		info user vanhoenackerl09@dbz.be
		info user vanweldenx09@dbz.be
		info user verhaestk09@dbz.be
		info user vervustm09@dbz.be
		info user vivilek09@dbz.be
		info user chihaouis12@dbz.be
		info user demeyerj09@dbz.be
		info user demolderl09@dbz.be
		info user despiegeleerk09@dbz.be
		info user detorckb09@dbz.be
		info user devogelaeret09@dbz.be
		info user deweirdtl09@dbz.be
		info user dosscheg09@dbz.be
		info user gurickxn09@dbz.be
		info user hauttekeeten09@dbz.be
		info user joosm09@dbz.be
		info user joosz09@dbz.be
		info user lesagea09@dbz.be
		info user lesagel09@dbz.be
		info user lioend09@dbz.be
		info user ramanj09@dbz.be
		info user stuyckl09@dbz.be
		info user vandeveireg09@dbz.be
		info user vangeluwedebe11@dbz.be
		info user vanpouckel09@dbz.be
		info user verhaegenm09@dbz.be
		info user asselmanb09@dbz.be
		info user bruynoghes09@dbz.be
		info user delodderes09@dbz.be
		info user demuynckz09@dbz.be
		info user depauwe09@dbz.be
		info user derooi09@dbz.be
		info user deroom09@dbz.be
		info user desmeti09@dbz.be
		info user dhondtn09@dbz.be
		info user dhontg09@dbz.be
		info user ingelaereb09@dbz.be
		info user leclercqg09@dbz.be
		info user lenaertsf09@dbz.be
		info user magniettez09@dbz.be
		info user roelantsj09@dbz.be
		info user vancauwenbergheh09@dbz.be
		info user vandeveldet09@dbz.be
		info user vanleenec09@dbz.be
		info user vanmaelea09@dbz.be
		info user vercauterenh09@dbz.be
		info user verleyenc09@dbz.be
		info user vynckej09@dbz.be
		info user weynss11@dbz.be
		info user claeysb09@dbz.be
		info user deconinckn09@dbz.be
		info user dekeuleneirv09@dbz.be
		info user depreestera09@dbz.be
		info user derijcket09@dbz.be
		info user laroyj09@dbz.be
		info user peetersf09@dbz.be
		info user buysseo09@dbz.be
		info user debrouwerec09@dbz.be
		info user desmeta09@dbz.be
		info user desmete111@dbz.be
		info user vandendriesschem09@dbz.be
		info user vervaekep09@dbz.be
		info user wattys09@dbz.be
		info user behaeghee09@dbz.be
		info user buyssel09@dbz.be
		info user cannootk09@dbz.be
		info user claeyssensa10@dbz.be
		info user daveye09@dbz.be
		info user debruynej09@dbz.be
		info user decortea09@dbz.be
		info user deloofm09@dbz.be
		info user demolderr09@dbz.be
		info user desutters09@dbz.be
		info user dewildeb09@dbz.be
		info user dujardinp09@dbz.be
		info user eeckhouts091@dbz.be
		info user ghiottoc09@dbz.be
		info user haeryncka09@dbz.be
		info user kamermansc09@dbz.be
		info user pypeh09@dbz.be
		info user vanavermaeta09@dbz.be
		info user vancauwenberghea09@dbz.be
		info user vancauwenberghej09@dbz.be
		info user vanderschuerene09@dbz.be
		info user vanoverbergheb09@dbz.be
		info user verstappej09@dbz.be
		info user vertriestf09@dbz.be
		info user volckaerta09@dbz.be
		info user bekaertl09@dbz.be
		info user bradtc09@dbz.be
		info user buylep09@dbz.be
		info user clevisw09@dbz.be
		info user cousaerts09@dbz.be
		info user degrooten09@dbz.be
		info user depauws09@dbz.be
		info user dereggea09@dbz.be
		info user desmetj091@dbz.be
		info user hofmann09@dbz.be
		info user hoogewysg09@dbz.be
		info user huysentruytd09@dbz.be
		info user kervyndevolkc10@dbz.be
		info user lievensa09@dbz.be
		info user muijsp09@dbz.be
		info user quataerth09@dbz.be
		info user schepensm09@dbz.be
		info user schoenmaekerse09@dbz.be
		info user tackf09@dbz.be
		info user tyberghienm09@dbz.be
		info user vandenhemeln09@dbz.be
		info user vandeveldec09@dbz.be
		info user verrethj09@dbz.be
		info user baetene09@dbz.be
		info user casteelsh09@dbz.be
		info user cuyversh09@dbz.be
		info user defooza09@dbz.be
		info user degraevep09@dbz.be
		info user deprezl09@dbz.be
		info user desimpelaerek09@dbz.be
		info user desmedtj09@dbz.be
		info user desmetb09@dbz.be
		info user devylderr09@dbz.be
		info user haverbekej09@dbz.be
		info user kerckhaertj09@dbz.be
		info user leymant09@dbz.be
		info user mareenm09@dbz.be
		info user mortierj09@dbz.be
		info user sabbem09@dbz.be
		info user steenackera09@dbz.be
		info user stormsm09@dbz.be
		info user vandammej09@dbz.be
		info user vanlangenhoves091@dbz.be
		info user vansteenbergd10@dbz.be
		info user vrombautj09@dbz.be
		info user willaertl09@dbz.be
		info user algoedl09@dbz.be
		info user budimanj09@dbz.be
		info user degreven09@dbz.be
		info user delangej09@dbz.be
		info user depelsemaekerr09@dbz.be
		info user depoorteren09@dbz.be
		info user depuydta09@dbz.be
		info user deridders09@dbz.be
		info user deschuijmerj09@dbz.be
		info user dujardinb09@dbz.be
		info user hamerlinckl09@dbz.be
		info user klingelew09@dbz.be
		info user rasschaertt09@dbz.be
		info user stas-orbanj09@dbz.be
		info user tacks09@dbz.be
		info user unruhl09@dbz.be
		info user vandercruyssenh09@dbz.be
		info user vandeveldea09@dbz.be
		info user vanhoecken09@dbz.be
		info user vanoosth09@dbz.be
		info user verschurena09@dbz.be
		info user wallaysi09@dbz.be
		info user willemsw09@dbz.be
		info user zwaenepoela09@dbz.be
		info user calmeynm10@dbz.be
		info user casteelsa09@dbz.be
		info user collumbiena11@dbz.be
		info user coppenstamayom09@dbz.be
		info user demana091@dbz.be
		info user duyckc09@dbz.be
		info user fiersa09@dbz.be
		info user filliersa11@dbz.be
		info user liermanj09@dbz.be
		info user martensn09@dbz.be
		info user peirej09@dbz.be
		info user peirsmant09@dbz.be
		info user saeysr09@dbz.be
		info user scheerlynckb09@dbz.be
		info user strybole09@dbz.be
		info user vandemoortelem09@dbz.be
		info user vandenabeelej09@dbz.be
		info user vandeneynder09@dbz.be
		info user vaneeckhoutm09@dbz.be
		info user verschurena12@dbz.be
		info user vervynckts09@dbz.be
		info user verzeles09@dbz.be
		info user volckaertl09@dbz.be
		info user volckaerts09@dbz.be
		info user willekensa09@dbz.be
		info user antropv07@dbz.be
		info user callewaertb08@dbz.be
		info user derveauxl08@dbz.be
		info user deserannol08@dbz.be
		info user desmetl08@dbz.be
		info user dewildej081@dbz.be
		info user dewitter08@dbz.be
		info user dhondta08@dbz.be
		info user dhontj08@dbz.be
		info user dosschem08@dbz.be
		info user haesebeytl08@dbz.be
		info user hemelsoete08@dbz.be
		info user kunnenm08@dbz.be
		info user lampensm08@dbz.be
		info user leerling4t10@dbz.be
		info user matthysl081@dbz.be
		info user meersmani08@dbz.be
		info user naessense08@dbz.be
		info user parmentiera08@dbz.be
		info user pattynt08@dbz.be
		info user roelandtsl08@dbz.be
		info user schaubroeckm08@dbz.be
		info user thienpontm08@dbz.be
		info user vandesteenei08@dbz.be
		info user willemsl08@dbz.be
		info user amante08@dbz.be
		info user baekelandh08@dbz.be
		info user dekesela11@dbz.be
		info user denysj08@dbz.be
		info user depotterg11@dbz.be
		info user depreiterea08@dbz.be
		info user gevaertm08@dbz.be
		info user lefeverei08@dbz.be
		info user ostr08@dbz.be
		info user vanacoleyent08@dbz.be
		info user vandenabeelee08@dbz.be
		info user vandendriesv08@dbz.be
		info user vandenheedel08@dbz.be
		info user vanhoev08@dbz.be
		info user vercamero08@dbz.be
		info user verhaeghed08@dbz.be
		info user verschaerenr08@dbz.be
		info user vervaekec11@dbz.be
		info user vuyer08@dbz.be
		info user wattem08@dbz.be
		info user brackel08@dbz.be
		info user cerieze08@dbz.be
		info user cnuddet08@dbz.be
		info user crabbew09@dbz.be
		info user declercqk08@dbz.be
		info user decockc08@dbz.be
		info user dekeysera08@dbz.be
		info user deryckec08@dbz.be
		info user devogelaeree08@dbz.be
		info user dhondtc08@dbz.be
		info user lybaerta08@dbz.be
		info user petereynsj08@dbz.be
		info user pirellil08@dbz.be
		info user poppel08@dbz.be
		info user schietsej08@dbz.be
		info user somvillet08@dbz.be
		info user vandenbosschec08@dbz.be
		info user vandenhooffp12@dbz.be
		info user vanhaesebroecks08@dbz.be
		info user vanhoves08@dbz.be
		info user vanpeteghemn08@dbz.be
		info user vanthuynej08@dbz.be
		info user verleyenj08@dbz.be
		info user vermeulens08@dbz.be
		info user vijvermanp08@dbz.be
		info user dedeckerr08@dbz.be
		info user kunnenj08@dbz.be
		info user rottiersa08@dbz.be
		info user sebrechtsi08@dbz.be
		info user tonolie08@dbz.be
		info user vandenbroeckej08@dbz.be
		info user vandorenf08@dbz.be
		info user cartone08@dbz.be
		info user danneelss08@dbz.be
		info user debaeree08@dbz.be
		info user dejaegherf08@dbz.be
		info user derooo08@dbz.be
		info user deroree08@dbz.be
		info user kygneep08@dbz.be
		info user laertem08@dbz.be
		info user maese08@dbz.be
		info user rabautj08@dbz.be
		info user stremusd08@dbz.be
		info user vancauwenberghee08@dbz.be
		info user vandenabbeelem08@dbz.be
		info user vandenheedea08@dbz.be
		info user vanvlierberghej08@dbz.be
		info user verhasselta08@dbz.be
		info user vermaerckel08@dbz.be
		info user westp08@dbz.be
		info user allemanm08@dbz.be
		info user bruyneela08@dbz.be
		info user casteelsf08@dbz.be
		info user coppensm08@dbz.be
		info user decockerj08@dbz.be
		info user deconinckl08@dbz.be
		info user delbaeref08@dbz.be
		info user deslooverel08@dbz.be
		info user desmete08@dbz.be
		info user devreesec08@dbz.be
		info user dewildej08@dbz.be
		info user dewildem08@dbz.be
		info user dewitted08@dbz.be
		info user dosschef08@dbz.be
		info user laevensm08@dbz.be
		info user lagae08@dbz.be
		info user meylemansn08@dbz.be
		info user provosta08@dbz.be
		info user vancampi08@dbz.be
		info user vanhavermaetj08@dbz.be
		info user vanquaillec08@dbz.be
		info user verheyej08@dbz.be
		info user vinckev08@dbz.be
		info user wollaertl08@dbz.be
		info user brains08@dbz.be
		info user bruneelr08@dbz.be
		info user danhieuxs08@dbz.be
		info user debruynej08@dbz.be
		info user derool08@dbz.be
		info user devolders08@dbz.be
		info user heysej08@dbz.be
		info user lagaertd08@dbz.be
		info user matthysl08@dbz.be
		info user messiaenk08@dbz.be
		info user moreaun08@dbz.be
		info user noyens08@dbz.be
		info user pismanb08@dbz.be
		info user uyttenhovet08@dbz.be
		info user vancoppernollea08@dbz.be
		info user vancoppernollet08@dbz.be
		info user vandemoortelef08@dbz.be
		info user vandenberghec08@dbz.be
		info user vandeveldek08@dbz.be
		info user vandevijvers08@dbz.be
		info user vanlangenhovez08@dbz.be
		info user vanrentergheml08@dbz.be
		info user vanschoorisseg08@dbz.be
		info user vanstraeseelek08@dbz.be
		info user vermeirev08@dbz.be
		info user bontel08@dbz.be
		info user casteleint08@dbz.be
		info user creveaus08@dbz.be
		info user daelemanst08@dbz.be
		info user debruyna08@dbz.be
		info user decuypert08@dbz.be
		info user degraevea08@dbz.be
		info user demeyerr08@dbz.be
		info user desmetf08@dbz.be
		info user huysmand08@dbz.be
		info user laevensf08@dbz.be
		info user lievensl08@dbz.be
		info user maebei08@dbz.be
		info user maesj08@dbz.be
		info user minjauwe08@dbz.be
		info user oliviers08@dbz.be
		info user redantt08@dbz.be
		info user remmeryj08@dbz.be
		info user tacheletf08@dbz.be
		info user taildemanm08@dbz.be
		info user vanaudenaerdes08@dbz.be
		info user vandenhendec10@dbz.be
		info user vanhoegaerdenl08@dbz.be
		info user vannuth08@dbz.be
		info user verheugem08@dbz.be
		info user wandelsa08@dbz.be
		info user blommes08@dbz.be
		info user buseyneb08@dbz.be
		info user coetsiert08@dbz.be
		info user deknibberv08@dbz.be
		info user delensv08@dbz.be
		info user derooj08@dbz.be
		info user dosschee08@dbz.be
		info user eeckhoutj08@dbz.be
		info user lagastj08@dbz.be
		info user lamquetm08@dbz.be
		info user laroyc08@dbz.be
		info user ogierse08@dbz.be
		info user pauwelync08@dbz.be
		info user philipst08@dbz.be
		info user schepersm08@dbz.be
		info user schiettecattet08@dbz.be
		info user stevensl08@dbz.be
		info user vanherreweghel08@dbz.be
		info user vanmarckev08@dbz.be
		info user vanongevallem08@dbz.be
		info user verstraeteg08@dbz.be
		info user waeterloosj08@dbz.be
		info user weyersb08@dbz.be
		info user adhikaris08@dbz.be
		info user baeyenst08@dbz.be
		info user battiaup08@dbz.be
		info user braetj08@dbz.be
		info user brysbaerts08@dbz.be
		info user christiaensb08@dbz.be
		info user decocks08@dbz.be
		info user deprezp08@dbz.be
		info user desmetk08@dbz.be
		info user gesquieres10@dbz.be
		info user goeminnej08@dbz.be
		info user kerckaertj10@dbz.be
		info user ongenaetj08@dbz.be
		info user pennincke08@dbz.be
		info user schwarzj11@dbz.be
		info user slabbinckw08@dbz.be
		info user steenackerk08@dbz.be
		info user talloenj08@dbz.be
		info user vanbelleghemm08@dbz.be
		info user vandenbruwaenes07@dbz.be
		info user vandenreydte08@dbz.be
		info user vandermeerschw08@dbz.be
		info user vangampelaereb08@dbz.be
		info user wiemem08@dbz.be
		info user wuylensn08@dbz.be
		info user booneg08@dbz.be
		info user boss08@dbz.be
		info user deblanderw08@dbz.be
		info user desmete081@dbz.be
		info user desutterp08@dbz.be
		info user ducheynet08@dbz.be
		info user hartmannt08@dbz.be
		info user hoornaertf08@dbz.be
		info user kollarackalm08@dbz.be
		info user leroyt08@dbz.be
		info user matthijse08@dbz.be
		info user matthysp10@dbz.be
		info user moonsm08@dbz.be
		info user peirsmanf08@dbz.be
		info user pierloote08@dbz.be
		info user reunesm08@dbz.be
		info user roelss08@dbz.be
		info user roosenl08@dbz.be
		info user segerss08@dbz.be
		info user themistocleousa07@dbz.be
		info user vandewalled08@dbz.be
		info user vanhaeverbekea08@dbz.be
		info user vanhaeverbekem08@dbz.be
		info user vannieuwenhuyzel08@dbz.be
		info user verzeleb08@dbz.be
		info user bese08@dbz.be
		info user cornils08@dbz.be
		info user danneelsa08@dbz.be
		info user delangem08@dbz.be
		info user demeyern08@dbz.be
		info user deschepperbrm08@dbz.be
		info user devriezee08@dbz.be
		info user eeckhoutm08@dbz.be
		info user gerardip08@dbz.be
		info user gouwyr08@dbz.be
		info user loccufiere08@dbz.be
		info user poelmann08@dbz.be
		info user raesn08@dbz.be
		info user schelstraetej08@dbz.be
		info user somersp08@dbz.be
		info user stas-orbanb08@dbz.be
		info user vandepittet11@dbz.be
		info user vandevijvers081@dbz.be
		info user vanhoolandt08@dbz.be
		info user vanlaeckel08@dbz.be
		info user verbeurgta11@dbz.be
		info user verhaeghem08@dbz.be
		info user verkerkenm08@dbz.be
		info user vindevogeln08@dbz.be
		info user wallaertp08@dbz.be
		info user bastiaansenj07@dbz.be
		info user braeckmane07@dbz.be
		info user caillej07@dbz.be
		info user clausf07@dbz.be
		info user dechaenes07@dbz.be
		info user decortel07@dbz.be
		info user delensa07@dbz.be
		info user dewildemanv07@dbz.be
		info user dewittec07@dbz.be
		info user horatscheki07@dbz.be
		info user leecet07@dbz.be
		info user leerling5t10@dbz.be
		info user maeneh07@dbz.be
		info user petriq07@dbz.be
		info user rosiang07@dbz.be
		info user schattemanf07@dbz.be
		info user valckes07@dbz.be
		info user vandenbroecker07@dbz.be
		info user vannutl07@dbz.be
		info user vanpouckej11@dbz.be
		info user verbruggenc07@dbz.be
		info user vynckea07@dbz.be
		info user claeysbouuaertl07@dbz.be
		info user debruynek07@dbz.be
		info user desmulg07@dbz.be
		info user dewaegenaereb07@dbz.be
		info user hoebekea07@dbz.be
		info user maesl07@dbz.be
		info user meerssemane07@dbz.be
		info user vanoostendef07@dbz.be
		info user verstichelm07@dbz.be
		info user wallaysj07@dbz.be
		info user bossaertl07@dbz.be
		info user claeysl07@dbz.be
		info user claeyst07@dbz.be
		info user dbzvot07@dbz.be
		info user delangel11@dbz.be
		info user dewinterl07@dbz.be
		info user dewittem06@dbz.be
		info user eeckhoutw07@dbz.be
		info user garrej07@dbz.be
		info user hansesh11@dbz.be
		info user matthysl07@dbz.be
		info user merganj07@dbz.be
		info user segersw07@dbz.be
		info user tacka07@dbz.be
		info user vandervekenv07@dbz.be
		info user vercauterent07@dbz.be
		info user borremansc07@dbz.be
		info user demolderp07@dbz.be
		info user dermauxt07@dbz.be
		info user desmetp07@dbz.be
		info user roelantsm07@dbz.be
		info user sebrechtsd07@dbz.be
		info user vrielinckr07@dbz.be
		info user waesc07@dbz.be
		info user batailliel07@dbz.be
		info user daoudim07@dbz.be
		info user debaetsv07@dbz.be
		info user jansec07@dbz.be
		info user vanderplaetsenr07@dbz.be
		info user vanhoenackern07@dbz.be
		info user vanneremb07@dbz.be
		info user vanrenterghemm07@dbz.be
		info user willaertj07@dbz.be
		info user bontem07@dbz.be
		info user debruynej07@dbz.be
		info user defrancqc07@dbz.be
		info user demerlierm07@dbz.be
		info user demuynckm07@dbz.be
		info user dewilden07@dbz.be
		info user fallon-kunds07@dbz.be
		info user fiersm07@dbz.be
		info user garrem07@dbz.be
		info user lemeireb07@dbz.be
		info user lioent07@dbz.be
		info user lippenss07@dbz.be
		info user meylemansi07@dbz.be
		info user saeysj07@dbz.be
		info user sprangersb07@dbz.be
		info user tacky07@dbz.be
		info user tempelsc07@dbz.be
		info user tinelh07@dbz.be
		info user vanhuylenbroecki07@dbz.be
		info user vanimpej07@dbz.be
		info user verbiestb07@dbz.be
		info user buyssensw07@dbz.be
		info user decleerp07@dbz.be
		info user lamona07@dbz.be
		info user naessenso07@dbz.be
		info user pootl07@dbz.be
		info user vandesteenet07@dbz.be
		info user vanovoste07@dbz.be
		info user willemse07@dbz.be
		info user andriesj07@dbz.be
		info user bosmansc07@dbz.be
		info user boxyp07@dbz.be
		info user bradtl07@dbz.be
		info user debaetsl07@dbz.be
		info user debrabanderl07@dbz.be
		info user demeyerp07@dbz.be
		info user deruyterp07@dbz.be
		info user hofmanr07@dbz.be
		info user jansl07@dbz.be
		info user leynsc07@dbz.be
		info user lootensm07@dbz.be
		info user poelmans07@dbz.be
		info user tackl07@dbz.be
		info user vandewalles07@dbz.be
		info user vandorpet07@dbz.be
		info user vanhover07@dbz.be
		info user vanoverscheldeh071@dbz.be
		info user vanoverscheldeh07@dbz.be
		info user vanpoeckd07@dbz.be
		info user verbruggenk07@dbz.be
		info user vermeulent07@dbz.be
		info user vrombautt07@dbz.be
		info user weynsm11@dbz.be
		info user willekensm07@dbz.be
		info user baetenf07@dbz.be
		info user deraedtl07@dbz.be
		info user germonpref07@dbz.be
		info user hermiej07@dbz.be
		info user ooghes11@dbz.be
		info user beddeleemh07@dbz.be
		info user blommea07@dbz.be
		info user boerss07@dbz.be
		info user coensk07@dbz.be
		info user collumbienp07@dbz.be
		info user demeyerm07@dbz.be
		info user desmett07@dbz.be
		info user devilderj07@dbz.be
		info user devleeschauwerh07@dbz.be
		info user drieghec07@dbz.be
		info user droesbekeh07@dbz.be
		info user ghyselincke07@dbz.be
		info user goethalsl11@dbz.be
		info user liebeherrm07@dbz.be
		info user mertensa07@dbz.be
		info user meulemanst07@dbz.be
		info user rogiero07@dbz.be
		info user smetm10@dbz.be
		info user vandenherrewegeng07@dbz.be
		info user vanderhaeghen07@dbz.be
		info user vandewallel07@dbz.be
		info user vanimpek07@dbz.be
		info user vekemanr07@dbz.be
		info user verbanckj07@dbz.be
		info user verleyenl07@dbz.be
		info user decokere07@dbz.be
		info user deschrijverc07@dbz.be
		info user dewiti07@dbz.be
		info user holbrouckj07@dbz.be
		info user petersm07@dbz.be
		info user vercammenp07@dbz.be
		info user bauwensm07@dbz.be
		info user brackej07@dbz.be
		info user bulensc07@dbz.be
		info user charlel07@dbz.be
		info user claeysj07@dbz.be
		info user crooe07@dbz.be
		info user cuvelierm07@dbz.be
		info user cuyverss07@dbz.be
		info user decuyperh07@dbz.be
		info user deprezm07@dbz.be
		info user dhaenensm07@dbz.be
		info user dhondtm07@dbz.be
		info user hillaerta07@dbz.be
		info user kintl07@dbz.be
		info user klingelep07@dbz.be
		info user leclercqa07@dbz.be
		info user lefebvres07@dbz.be
		info user potv07@dbz.be
		info user rombautm07@dbz.be
		info user schockaerte07@dbz.be
		info user stuyckf07@dbz.be
		info user vandepittep07@dbz.be
		info user vandererfvenj07@dbz.be
		info user vanderstedet07@dbz.be
		info user vermieschr07@dbz.be
		info user bauwensn07@dbz.be
		info user behaeghel07@dbz.be
		info user buffela07@dbz.be
		info user coussementm07@dbz.be
		info user daveyl07@dbz.be
		info user debruynh07@dbz.be
		info user degheselles07@dbz.be
		info user delodderee07@dbz.be
		info user dereggel07@dbz.be
		info user dossches07@dbz.be
		info user heysej07@dbz.be
		info user kinolik07@dbz.be
		info user mullerz07@dbz.be
		info user perezherreroc07@dbz.be
		info user pietersb07@dbz.be
		info user pirons07@dbz.be
		info user vancauwenbergher07@dbz.be
		info user vandaelk07@dbz.be
		info user vandenabbeeler07@dbz.be
		info user vangeluwedebt07@dbz.be
		info user vanpouckej07@dbz.be
		info user vermassenh07@dbz.be
		info user algoedc07@dbz.be
		info user clementv07@dbz.be
		info user debackers07@dbz.be
		info user debeufs07@dbz.be
		info user decleyree07@dbz.be
		info user devogelaeres07@dbz.be
		info user devriendtn07@dbz.be
		info user dewildeb07@dbz.be
		info user dosschep07@dbz.be
		info user ingelaeret07@dbz.be
		info user lutsg07@dbz.be
		info user merckxl07@dbz.be
		info user pietersd07@dbz.be
		info user polletl07@dbz.be
		info user sabbez07@dbz.be
		info user segersn07@dbz.be
		info user vanbeirsc07@dbz.be
		info user vandenbruwaenel07@dbz.be
		info user vandesompeles07@dbz.be
		info user vandeveldel07@dbz.be
		info user vanhecks07@dbz.be
		info user vervusts07@dbz.be
		info user annem06@dbz.be
		info user brainm06@dbz.be
		info user buysel06@dbz.be
		info user christiaensa06@dbz.be
		info user claermanc06@dbz.be
		info user claermanj06@dbz.be
		info user cornils06@dbz.be
		info user declerckm06@dbz.be
		info user declercqc06@dbz.be
		info user depaepem06@dbz.be
		info user dewispelaerel06@dbz.be
		info user dhondtm06@dbz.be
		info user dhontf06@dbz.be
		info user flammange06@dbz.be
		info user franssenp06@dbz.be
		info user frickelm05@dbz.be
		info user maenea06@dbz.be
		info user matthysa06@dbz.be
		info user mestdachj06@dbz.be
		info user meyerss06@dbz.be
		info user paelincka06@dbz.be
		info user vandenbossched06@dbz.be
		info user vandenbrouckem06@dbz.be
		info user vanderstichelem06@dbz.be
		info user vanlandtschootea06@dbz.be
		info user braeckmanl06@dbz.be
		info user braets06@dbz.be
		info user brantegemg06@dbz.be
		info user callebautp06@dbz.be
		info user claeysd06@dbz.be
		info user debruynes06@dbz.be
		info user dekeysere06@dbz.be
		info user desplenterm11@dbz.be
		info user dhaesee06@dbz.be
		info user ducheynel06@dbz.be
		info user fauconnierk06@dbz.be
		info user gerardr06@dbz.be
		info user gunsta06@dbz.be
		info user hachej06@dbz.be
		info user haegemanl06@dbz.be
		info user hoogewysf10@dbz.be
		info user legeine06@dbz.be
		info user leroyn06@dbz.be
		info user remuej06@dbz.be
		info user rogiersj06@dbz.be
		info user sieronm06@dbz.be
		info user smaggee06@dbz.be
		info user vandenabeeler06@dbz.be
		info user vandenberghem11@dbz.be
		info user vekemanw06@dbz.be
		info user verhelstl06@dbz.be
		info user decocks06@dbz.be
		info user mortreul06@dbz.be
		info user vermeulenf06@dbz.be
		info user vijvermant06@dbz.be
		info user vincentl06@dbz.be
		info user borremansm06@dbz.be
		info user dhulsterm06@dbz.be
		info user dosschea06@dbz.be
		info user gheeraertm06@dbz.be
		info user goossensy06@dbz.be
		info user laertem06@dbz.be
		info user leerlingt11@dbz.be
		info user pelemanp06@dbz.be
		info user perezherreroa06@dbz.be
		info user pote06@dbz.be
		info user stubbec06@dbz.be
		info user vangoethema10@dbz.be
		info user vanrossema06@dbz.be
		info user vanvlierbergher06@dbz.be
		info user demeulenaerel06@dbz.be
		info user descheppere06@dbz.be
		info user faelensg06@dbz.be
		info user geirnaertn06@dbz.be
		info user lerminiauxl06@dbz.be
		info user matthijsd06@dbz.be
		info user matthyss06@dbz.be
		info user mourisseb06@dbz.be
		info user standaertg06@dbz.be
		info user vandermeerens06@dbz.be
		info user vanderstichelej06@dbz.be
		info user vanhovel06@dbz.be
		info user verstichelj06@dbz.be
		info user zwaenepoela06@dbz.be
		info user coetsierg06@dbz.be
		info user danhieuxt06@dbz.be
		info user daveyc06@dbz.be
		info user deriddern06@dbz.be
		info user fernandez-alonsoj06@dbz.be
		info user laertef06@dbz.be
		info user liuy06@dbz.be
		info user matthyss061@dbz.be
		info user naessensc06@dbz.be
		info user pirons06@dbz.be
		info user serruysm06@dbz.be
		info user somersj06@dbz.be
		info user vandammea06@dbz.be
		info user vanlanckere06@dbz.be
		info user willemsv06@dbz.be
		info user deconinckb06@dbz.be
		info user deconinckn06@dbz.be
		info user delruej06@dbz.be
		info user deroof06@dbz.be
		info user desmetb06@dbz.be
		info user fouquaerts06@dbz.be
		info user geenensb06@dbz.be
		info user ghekierec06@dbz.be
		info user mortiert06@dbz.be
		info user nauwynckw06@dbz.be
		info user nolletg06@dbz.be
		info user nolletj06@dbz.be
		info user ooghes06@dbz.be
		info user pismans06@dbz.be
		info user reynaerta06@dbz.be
		info user roelensm06@dbz.be
		info user schroerl06@dbz.be
		info user stevensj06@dbz.be
		info user vandeneyndem06@dbz.be
		info user vanderstraetenj06@dbz.be
		info user vanrenterghems06@dbz.be
		info user verbeurgta06@dbz.be
		info user vermeulens06@dbz.be
		info user adamsl06@dbz.be
		info user clarysl06@dbz.be
		info user coenegrachtss10@dbz.be
		info user cooremanv06@dbz.be
		info user decatellet06@dbz.be
		info user decoomanb06@dbz.be
		info user dekerpell06@dbz.be
		info user depesteles06@dbz.be
		info user desmetj06@dbz.be
		info user detroyerj06@dbz.be
		info user geirnaertl06@dbz.be
		info user kerckhaertc06@dbz.be
		info user lagav06@dbz.be
		info user maeyensw06@dbz.be
		info user nijsl06@dbz.be
		info user raesk06@dbz.be
		info user ruysbergha06@dbz.be
		info user scheerlyncks06@dbz.be
		info user steenackerr06@dbz.be
		info user tachelete06@dbz.be
		info user vangansbeked06@dbz.be
		info user vanlerbeirghem06@dbz.be
		info user wallaerta06@dbz.be
		info user wuylensa06@dbz.be
		info user zamane06@dbz.be
		info user bouillotm11@dbz.be
		info user comhairem06@dbz.be
		info user debruyckery06@dbz.be
		info user denysa06@dbz.be
		info user desmetj061@dbz.be
		info user devroet06@dbz.be
		info user facqe06@dbz.be
		info user gobertm06@dbz.be
		info user janssenss06@dbz.be
		info user laroym06@dbz.be
		info user mineurc06@dbz.be
		info user muylaerts06@dbz.be
		info user pauwelsa06@dbz.be
		info user tanh06@dbz.be
		info user timmermanv06@dbz.be
		info user vanbesouww06@dbz.be
		info user vandenheedek06@dbz.be
		info user vandeveldes06@dbz.be
		info user vanlaeckel06@dbz.be
		info user vynckek06@dbz.be
		info user lauwaertsf06@dbz.be
		info user segersl06@dbz.be
		info user amants06@dbz.be
		info user billiauws06@dbz.be
		info user bogaerta06@dbz.be
		info user colemanb06@dbz.be
		info user colpaerta06@dbz.be
		info user debysera06@dbz.be
		info user dutordoirv06@dbz.be
		info user essela06@dbz.be
		info user hansest11@dbz.be
		info user lenoirb06@dbz.be
		info user lievensk06@dbz.be
		info user loccufiere06@dbz.be
		info user matthysn06@dbz.be
		info user meiree06@dbz.be
		info user plouvierc06@dbz.be
		info user stepmang06@dbz.be
		info user vanbetsbruggeg06@dbz.be
		info user vanderstichelej061@dbz.be
		info user vanhavermaetj06@dbz.be
		info user vanhuffeln06@dbz.be
		info user vierinn06@dbz.be
		info user baertk06@dbz.be
		info user bekes06@dbz.be
		info user benoott06@dbz.be
		info user bontej06@dbz.be
		info user bottermana06@dbz.be
		info user brall06@dbz.be
		info user debusscherc06@dbz.be
		info user dechaenep06@dbz.be
		info user dekeysero06@dbz.be
		info user depaepet06@dbz.be
		info user dewachterm06@dbz.be
		info user dotselaerea06@dbz.be
		info user gouwyh06@dbz.be
		info user hillewaerem06@dbz.be
		info user maebej06@dbz.be
		info user maesl06@dbz.be
		info user poelmang06@dbz.be
		info user rotgensl06@dbz.be
		info user vandammem06@dbz.be
		info user vandenbroecket06@dbz.be
		info user vandenmeerssl06@dbz.be
		info user vandewielea06@dbz.be
		info user vanhootegemk06@dbz.be
		info user vanlanduytb06@dbz.be
		info user verstraetek06@dbz.be
		info user wallaertl06@dbz.be
		info user adhikaris11@dbz.be
		info user debeirr06@dbz.be
		info user debooserp06@dbz.be
		info user dekeukeleirel06@dbz.be
		info user dhooghew06@dbz.be
		info user garree06@dbz.be
		info user garrej06@dbz.be
		info user gevaertj06@dbz.be
		info user hartmannm06@dbz.be
		info user hoets06@dbz.be
		info user ingelsr06@dbz.be
		info user lootensl06@dbz.be
		info user manalilil06@dbz.be
		info user plovytm10@dbz.be
		info user schaumontd06@dbz.be
		info user schockaertl06@dbz.be
		info user schoenmaekersn06@dbz.be
		info user vancompernolleh06@dbz.be
		info user vandenheeded06@dbz.be
		info user vanhyftet06@dbz.be
		info user vanthuynej06@dbz.be
		info user waeterloosf06@dbz.be
		info user willemijnsj06@dbz.be
		info user wollaertl06@dbz.be";

		$arrcmds = explode("\n", $commands);

		foreach($arrcmds as $cmd)
		{
				
			$username = strstr($cmd, "info user ");
			$username = substr($username,10);
			$username = strstr($username,"@",true);
			
			$alias="";

			$res = GamExecutor::executeGamCommandGetResult($cmd);
				
			$arr = explode("\n", $res);
				
			$usenextline=false;
			foreach($arr as $line)
			{
				if($usenextline)
				{
					$alias = $line;
					break;
				}
				if(strstr($line,"Nicknames") !== false)
				{
					$usenextline = true;
				}
			}



			$myperson = Person::getPersonByUsername($username);
			
			if($myperson !== NULL)
			{
				$cfg = PlatformGA::getPlatformConfigByPersonId($myperson->getId());
				if($cfg === NULL)
				{
					$cfg = new PlatformGA();
					$cfg->setPersonId($myperson->getId());
					$cfg->setEnabled(true);
					$cfg->setAliasmail($alias);
					PlatformGA::addToPlatform($cfg);
				}else{
					$cfg->setAliasmail($alias);
					PlatformGA::updatePlatform($cfg);
				}
			}
			

		}


	}

}

class gappObj
{
	public $mail;
	public $type;

	public static function __set_state($arr)
	{
		echo "info user " . $arr["mail"] . "\n";

	}

	public function __construct($mail,$type)
	{
		$this->mail = $mail;
		$this->type = $type;
	}
}
